/-
The Aeneas model of `crates/con-ron-core`, committed and regenerated by
`scripts/extract.sh` (DESIGN.md §3.5, task #12).

`ConRon/Generated/{Types,Funs}.lean` are machine-generated and must never be
edited; `ConRon/Generated/{Types,Funs}External.lean` are the hand-written
`Rc` models of DESIGN.md §3.2 and are never overwritten.  The
`*_Template.lean` files are the regenerated statement of which holes exist;
they are deliberately *not* imported (they declare the same names as
`axiom`s), and `scripts/extract.sh` fails if a template lists an external the
hand-written file does not model.

Definitions live in the `ConRon.Generated` namespace, so a ported Rust
function `<module>::<fn>` is `ConRon.Generated.<module>.<fn>`.
-/
import ConRon.Generated.Types
import ConRon.Generated.Funs
