//! `ConLeche/Kernel/Basis/{Eq,Nat,PUnit,Empty,False,Quot}.lean` and
//! `ConLeche/Kernel/Basis.lean` — the **raw** pinned basis blocks: each block
//! exactly as an export carries it, the toolchain's `Init.Prelude`
//! declaration at the parser's raw binder annotations — plus the two tests
//! that recognise one in a stream record.
//!
//! **Why they are in the verified core.**  con-ron-core carries the
//! *annotated* blocks (`kernel::basis_tables`, `BasisKind.declsA`,
//! generated by task #22), which is what the installation stores; the raw
//! pins are what an incoming record is MATCHED against.  Until con-leche
//! task #293 that match was the parser's, and this module lived in the
//! unverified crate beside it (`con_ron::frontend::basis_raw`).  Task #293
//! moved the recognition into the fold: the decoder emits the file's records
//! and nothing else, `prepare_prelude` only reorders them, and it is
//! `check_decl` that recognises a block as one of the five pins
//! (`basis_pin_hit` below) and a `#QUOT` record — or the `Quot.sound` axiom
//! record — as the pinned quotient package's (`quot_pin_hit` below).  The
//! match is part of the verdict, so the pins and the two tests are part of
//! the verified core.
//!
//! **Why there are two tables.**  The raw pins could not be borrowed from
//! `basis_tables`: `canonEq` resets binder metadata and `IndCaps` on both
//! sides but compares a recursor rule's install-computed fields
//! (`ctorParams`, `fire`, `k`, `eta`, `paramsBlind`) verbatim, and the
//! annotated `Nat.rec` rule carries `ctorParams = 2`, `fire = .plain`,
//! `k = true`, `paramsBlind = true` where a parsed one carries the
//! placeholders.  A stream's `Nat` block would then never match the pin,
//! which is a verdict divergence, not a cosmetic one.  The module's own
//! tests check that claim both ways.
//!
//! con-leche's own module split is the same one for the same reason:
//! `Kernel/Basis.lean` (the raw pins) sits BELOW `Kernel/TypeChecker`
//! because "the kernel core needs the raw pins … and nothing else", and
//! `Kernel/BasisA.lean` sits above it.
//!
//! Written with con-ron-core's port of the raw-pin DSL
//! (`kernel::basis_builder`, task #18), so a reader can line each pin up
//! against `Init.Prelude` binder by binder exactly as in the Lean.  The
//! DSL's own deviation stands: `pi`/`piI`/`piA` are one function and
//! `lm`/`lmI` are one, because `Expr` carries neither a binder name nor a
//! binder info.

use crate::kernel::basis_builder::{ap2, ap3, bv, cnst, lm, pi, prop, srt, type1, u, u1};
use crate::kernel::basis_builder::{u1_n, u_n, v, v_n};
use crate::kernel::basis_names as bnm;
use crate::kernel::canon;
use crate::kernel::env;
use crate::kernel::env::{BasisKind, ConstantInfo, ConstantVal, IndCaps, QuotKind, RecRule};
use crate::kernel::expr;
use crate::kernel::expr::Expr;
use crate::kernel::name;
use crate::kernel::name::Name;
use crate::kernel::prop_when;

/// con-leche: none — `ConstantVal.mk` at the anonymous-constructor literal
/// `⟨name, lps, ty⟩` every pin below opens with.
pub fn cv(n: Name, lps: Vec<Name>, ty: Expr) -> ConstantVal {
    ConstantVal {
        name: n,
        level_params: lps,
        ty,
    }
}

/// con-leche: ConLeche/Kernel/Basis/Builder.lean:117-121 BasisDSL.rule
/// A raw iota rule: the install-computed fields (`ctorParams`, `fire`, `k`,
/// `eta`, `paramsBlind`) at their parse placeholders, which is what the
/// exporter emits and what `#annotate_basis` recomputes.
pub fn rule(ctor: Name, nfields: u64, rhs: Expr) -> RecRule {
    env::rec_rule_parsed(ctor, nfields, rhs)
}

// --- Eq --------------------------------------------------------------------

/// con-leche: ConLeche/Kernel/Basis/Eq.lean:22-28 eqRaw
/// `Eq.{u} {α : Sort u} : α → α → Prop`.
pub fn eq_raw() -> ConstantInfo {
    let caps = IndCaps {
        rule_k: true,
        ..env::ind_caps_default()
    };
    ConstantInfo::IndInfo(
        cv(
            bnm::eq_name(),
            vec![u_n()],
            pi(srt(u()), pi(bv(0), pi(bv(1), prop()))),
        ),
        caps,
    )
}

/// con-leche: ConLeche/Kernel/Basis/Eq.lean:30-36 eqReflRaw
/// `Eq.refl.{u} {α : Sort u} (a : α) : Eq α a a`.
pub fn eq_refl_raw() -> ConstantInfo {
    ConstantInfo::CtorInfo(
        cv(
            bnm::eq_refl_name(),
            vec![u_n()],
            pi(
                srt(u()),
                pi(
                    bv(0),
                    ap3(cnst(bnm::eq_name(), vec![u()]), bv(1), bv(0), bv(0)),
                ),
            ),
        ),
        2,
        0,
    )
}

/// con-leche: ConLeche/Kernel/Basis/Eq.lean:38-42 eqRecMotive
/// The motive of `Eq.rec`: `∀ (b : α) (t : Eq α a b), Sort u_1`, in the
/// `α`/`a` binder context (`α` is `#1`, `a` is `#0` at its head).
pub fn eq_rec_motive() -> Expr {
    pi(
        bv(1),
        pi(
            ap3(cnst(bnm::eq_name(), vec![u()]), bv(2), bv(1), bv(0)),
            srt(u1()),
        ),
    )
}

/// con-leche: none — `Eq.rec`'s `refl` minor premise, `motive a (Eq.refl α
/// a)`, which `eqRecRaw` spells twice (in its type and in its iota rule).
pub fn eq_rec_refl_dom() -> Expr {
    ap2(
        bv(0),
        bv(1),
        ap2(cnst(bnm::eq_refl_name(), vec![u()]), bv(2), bv(1)),
    )
}

/// con-leche: ConLeche/Kernel/Basis/Eq.lean:44-61 eqRecRaw
/// `Eq.rec.{u_1, u} {α : Sort u} {a : α} {motive : ∀ b, Eq α a b → Sort u_1}
/// (refl : motive a (Eq.refl α a)) {b : α} (t : Eq α a b) : motive b t`.
pub fn eq_rec_raw() -> ConstantInfo {
    ConstantInfo::RecInfo(
        cv(
            bnm::rec_of(bnm::eq_name()),
            vec![u1_n(), u_n()],
            pi(
                srt(u()),
                pi(
                    bv(0),
                    pi(
                        eq_rec_motive(),
                        pi(
                            eq_rec_refl_dom(),
                            pi(
                                bv(3),
                                pi(
                                    ap3(cnst(bnm::eq_name(), vec![u()]), bv(4), bv(3), bv(0)),
                                    ap2(bv(3), bv(1), bv(0)),
                                ),
                            ),
                        ),
                    ),
                ),
            ),
        ),
        5,
        4,
        vec![rule(
            bnm::eq_refl_name(),
            0,
            lm(
                srt(u()),
                lm(
                    bv(0),
                    lm(eq_rec_motive(), lm(eq_rec_refl_dom(), bv(0))),
                ),
            ),
        )],
    )
}

/// con-leche: ConLeche/Kernel/Basis/Eq.lean:63-64 eqBasis
/// The pinned `Eq` basis block, in install order.
pub fn eq_basis() -> Vec<ConstantInfo> {
    vec![eq_raw(), eq_refl_raw(), eq_rec_raw()]
}

// --- Nat -------------------------------------------------------------------

/// con-leche: ConLeche/Kernel/Basis/Nat.lean:21-22 natT
/// The type `Nat`, as a closed constant.
pub fn nat_t() -> Expr {
    cnst(bnm::nat_name(), Vec::new())
}

/// con-leche: ConLeche/Kernel/Basis/Nat.lean:24-26 natRaw
/// `Nat : Type`.
pub fn nat_raw() -> ConstantInfo {
    ConstantInfo::IndInfo(
        cv(bnm::nat_name(), Vec::new(), type1()),
        env::ind_caps_default(),
    )
}

/// con-leche: ConLeche/Kernel/Basis/Nat.lean:28-30 natZeroRaw
/// `Nat.zero : Nat`.
pub fn nat_zero_raw() -> ConstantInfo {
    ConstantInfo::CtorInfo(cv(bnm::nat_zero_name(), Vec::new(), nat_t()), 0, 0)
}

/// con-leche: ConLeche/Kernel/Basis/Nat.lean:32-34 natSuccRaw
/// `Nat.succ (n : Nat) : Nat`.
pub fn nat_succ_raw() -> ConstantInfo {
    ConstantInfo::CtorInfo(
        cv(bnm::nat_succ_name(), Vec::new(), pi(nat_t(), nat_t())),
        0,
        1,
    )
}

/// con-leche: ConLeche/Kernel/Basis/Nat.lean:36-37 natRecMotive
/// The motive of `Nat.rec`: `∀ (t : Nat), Sort u`.
pub fn nat_rec_motive() -> Expr {
    pi(nat_t(), srt(u()))
}

/// con-leche: ConLeche/Kernel/Basis/Nat.lean:39-44 natRecSucc
/// The successor minor premise of `Nat.rec`, in the `motive`/`zero` binder
/// context: `∀ (n : Nat), motive n → motive (Nat.succ n)`.
pub fn nat_rec_succ() -> Expr {
    pi(
        nat_t(),
        pi(
            expr::app(bv(2), bv(0)),
            expr::app(
                bv(3),
                expr::app(cnst(bnm::nat_succ_name(), Vec::new()), bv(1)),
            ),
        ),
    )
}

/// con-leche: none — `Nat.rec`'s `zero` minor premise, `motive Nat.zero`,
/// which `natRecRaw` spells three times (its type and both iota rules).
pub fn nat_rec_zero_dom() -> Expr {
    expr::app(bv(0), cnst(bnm::nat_zero_name(), Vec::new()))
}

/// con-leche: ConLeche/Kernel/Basis/Nat.lean:46-65 natRecRaw
/// `Nat.rec.{u} {motive : Nat → Sort u} (zero : motive Nat.zero)
/// (succ : ∀ n, motive n → motive n.succ) (t : Nat) : motive t`.
pub fn nat_rec_raw() -> ConstantInfo {
    let rec_name = bnm::rec_of(bnm::nat_name());
    ConstantInfo::RecInfo(
        cv(
            name::dup(&rec_name),
            vec![u_n()],
            pi(
                nat_rec_motive(),
                pi(
                    nat_rec_zero_dom(),
                    pi(
                        nat_rec_succ(),
                        pi(nat_t(), expr::app(bv(3), bv(0))),
                    ),
                ),
            ),
        ),
        3,
        3,
        vec![
            rule(
                bnm::nat_zero_name(),
                0,
                lm(
                    nat_rec_motive(),
                    lm(nat_rec_zero_dom(), lm(nat_rec_succ(), bv(1))),
                ),
            ),
            rule(
                bnm::nat_succ_name(),
                1,
                lm(
                    nat_rec_motive(),
                    lm(
                        nat_rec_zero_dom(),
                        lm(
                            nat_rec_succ(),
                            lm(
                                nat_t(),
                                ap2(
                                    bv(1),
                                    bv(0),
                                    expr::app(
                                        ap3(
                                            cnst(name::dup(&rec_name), vec![u()]),
                                            bv(3),
                                            bv(2),
                                            bv(1),
                                        ),
                                        bv(0),
                                    ),
                                ),
                            ),
                        ),
                    ),
                ),
            ),
        ],
    )
}

/// con-leche: ConLeche/Kernel/Basis/Nat.lean:67-68 natBasis
/// The pinned `Nat` basis block, in install order.
pub fn nat_basis() -> Vec<ConstantInfo> {
    vec![nat_raw(), nat_zero_raw(), nat_succ_raw(), nat_rec_raw()]
}

// --- PUnit -----------------------------------------------------------------

/// con-leche: ConLeche/Kernel/Basis/PUnit.lean:24-29 punitRaw
/// `PUnit.{u} : Sort u`.
pub fn punit_raw() -> ConstantInfo {
    let caps = IndCaps {
        eta: true,
        eta_ctor: bnm::punit_unit_name(),
        eta_params: 0,
        eta_fields: 0,
        unitlike: true,
        sort_z: prop_when::if_all_zero(vec![u_n()]),
        ..env::ind_caps_default()
    };
    ConstantInfo::IndInfo(cv(bnm::punit_name(), vec![u_n()], srt(u())), caps)
}

/// con-leche: ConLeche/Kernel/Basis/PUnit.lean:31-33 punitUnitRaw
/// `PUnit.unit.{u} : PUnit.{u}`.
pub fn punit_unit_raw() -> ConstantInfo {
    ConstantInfo::CtorInfo(
        cv(
            bnm::punit_unit_name(),
            vec![u_n()],
            cnst(bnm::punit_name(), vec![u()]),
        ),
        0,
        0,
    )
}

/// con-leche: ConLeche/Kernel/Basis/PUnit.lean:35-37 punitRecMotive
/// The motive of `PUnit.rec`: `∀ (t : PUnit.{u}), Sort u_1`.
pub fn punit_rec_motive() -> Expr {
    pi(cnst(bnm::punit_name(), vec![u()]), srt(u1()))
}

/// con-leche: none — `PUnit.rec`'s `unit` minor premise, `motive PUnit.unit`,
/// which `punitRecRaw` spells twice (its type and its iota rule).
pub fn punit_rec_unit_dom() -> Expr {
    expr::app(bv(0), cnst(bnm::punit_unit_name(), vec![u()]))
}

/// con-leche: ConLeche/Kernel/Basis/PUnit.lean:39-50 punitRecRaw
/// `PUnit.rec.{u_1, u} {motive : PUnit.{u} → Sort u_1} (unit : motive
/// PUnit.unit) (t : PUnit.{u}) : motive t`.
pub fn punit_rec_raw() -> ConstantInfo {
    ConstantInfo::RecInfo(
        cv(
            bnm::punit_rec_name(),
            vec![u1_n(), u_n()],
            pi(
                punit_rec_motive(),
                pi(
                    punit_rec_unit_dom(),
                    pi(
                        cnst(bnm::punit_name(), vec![u()]),
                        expr::app(bv(2), bv(0)),
                    ),
                ),
            ),
        ),
        2,
        2,
        vec![rule(
            bnm::punit_unit_name(),
            0,
            lm(punit_rec_motive(), lm(punit_rec_unit_dom(), bv(0))),
        )],
    )
}

/// con-leche: ConLeche/Kernel/Basis/PUnit.lean:52-53 punitBasis
/// The pinned `PUnit` basis block, in install order.
pub fn punit_basis() -> Vec<ConstantInfo> {
    vec![punit_raw(), punit_unit_raw(), punit_rec_raw()]
}

// --- Empty -----------------------------------------------------------------

/// con-leche: ConLeche/Kernel/Basis/Empty.lean:21-23 emptyRaw
/// `Empty : Type`.
pub fn empty_raw() -> ConstantInfo {
    ConstantInfo::IndInfo(
        cv(bnm::empty_name(), Vec::new(), type1()),
        env::ind_caps_default(),
    )
}

/// con-leche: ConLeche/Kernel/Basis/Empty.lean:25-32 emptyRecRaw
/// `Empty.rec.{u} (motive : Empty → Sort u) (t : Empty) : motive t`.  The
/// exporter emits the motive as an *explicit* binder here (there is no major
/// premise to infer it from).
pub fn empty_rec_raw() -> ConstantInfo {
    ConstantInfo::RecInfo(
        cv(
            bnm::rec_of(bnm::empty_name()),
            vec![u_n()],
            pi(
                pi(cnst(bnm::empty_name(), Vec::new()), srt(u())),
                pi(
                    cnst(bnm::empty_name(), Vec::new()),
                    expr::app(bv(1), bv(0)),
                ),
            ),
        ),
        1,
        1,
        Vec::new(),
    )
}

/// con-leche: ConLeche/Kernel/Basis/Empty.lean:34-35 emptyBasis
/// The pinned `Empty` basis block, in install order.
pub fn empty_basis() -> Vec<ConstantInfo> {
    vec![empty_raw(), empty_rec_raw()]
}

// --- False -----------------------------------------------------------------

/// con-leche: ConLeche/Kernel/Basis/False.lean:38-40 falseRaw
/// `False : Prop`.
pub fn false_raw() -> ConstantInfo {
    ConstantInfo::IndInfo(
        cv(bnm::false_name(), Vec::new(), prop()),
        env::ind_caps_default(),
    )
}

/// con-leche: ConLeche/Kernel/Basis/False.lean:42-49 falseRecRaw
/// `False.rec.{u} (motive : False → Sort u) (t : False) : motive t`.  The
/// exporter emits the motive as an *explicit* binder here, as for
/// `Empty.rec`.
pub fn false_rec_raw() -> ConstantInfo {
    ConstantInfo::RecInfo(
        cv(
            bnm::rec_of(bnm::false_name()),
            vec![u_n()],
            pi(
                pi(cnst(bnm::false_name(), Vec::new()), srt(u())),
                pi(
                    cnst(bnm::false_name(), Vec::new()),
                    expr::app(bv(1), bv(0)),
                ),
            ),
        ),
        1,
        1,
        Vec::new(),
    )
}

/// con-leche: ConLeche/Kernel/Basis/False.lean:51-52 falseBasis
/// The pinned `False` basis block, in install order.
pub fn false_basis() -> Vec<ConstantInfo> {
    vec![false_raw(), false_rec_raw()]
}

// --- Quot ------------------------------------------------------------------

/// con-leche: ConLeche/Kernel/Basis/Quot.lean:26-28 quotRel
/// The relation argument's type in the `α` binder context: `α → α → Prop`.
pub fn quot_rel() -> Expr {
    pi(bv(0), pi(bv(1), prop()))
}

/// con-leche: ConLeche/Kernel/Basis/Quot.lean:30-34 quotRaw
/// `Quot.{u} {α : Sort u} (r : α → α → Prop) : Sort u`.
pub fn quot_raw() -> ConstantInfo {
    ConstantInfo::IndInfo(
        cv(
            bnm::quot_name(),
            vec![u_n()],
            pi(srt(u()), pi(quot_rel(), srt(u()))),
        ),
        env::ind_caps_default(),
    )
}

/// con-leche: ConLeche/Kernel/Basis/Quot.lean:36-42 quotMkRaw
/// `Quot.mk.{u} {α : Sort u} (r : α → α → Prop) (a : α) : Quot α r`.
pub fn quot_mk_raw() -> ConstantInfo {
    ConstantInfo::CtorInfo(
        cv(
            bnm::quot_mk_name(),
            vec![u_n()],
            pi(
                srt(u()),
                pi(
                    quot_rel(),
                    pi(
                        bv(1),
                        ap2(cnst(bnm::quot_name(), vec![u()]), bv(2), bv(1)),
                    ),
                ),
            ),
        ),
        2,
        1,
    )
}

/// con-leche: ConLeche/Kernel/Basis/Quot.lean:44-45 quotLiftF
/// `Quot.lift`'s function slot, in the `α`/`r`/`β` context: `α → β`.
pub fn quot_lift_f() -> Expr {
    pi(bv(2), bv(1))
}

/// con-leche: ConLeche/Kernel/Basis/Quot.lean:47-53 quotLiftH
/// `Quot.lift`'s coherence slot, in the `α`/`r`/`β`/`f` context:
/// `∀ a b, r a b → f a = f b`.
pub fn quot_lift_h() -> Expr {
    pi(
        bv(3),
        pi(
            bv(4),
            pi(
                ap2(bv(4), bv(1), bv(0)),
                ap3(
                    cnst(bnm::eq_name(), vec![v()]),
                    bv(4),
                    expr::app(bv(3), bv(2)),
                    expr::app(bv(3), bv(1)),
                ),
            ),
        ),
    )
}

/// con-leche: ConLeche/Kernel/Basis/Quot.lean:55-72 quotLiftRaw
/// `Quot.lift.{u, v} {α : Sort u} {r : α → α → Prop} {β : Sort v}
/// (f : α → β) (h : ∀ a b, r a b → f a = f b) (q : Quot α r) : β`.
pub fn quot_lift_raw() -> ConstantInfo {
    ConstantInfo::RecInfo(
        cv(
            bnm::quot_lift_name(),
            vec![u_n(), v_n()],
            pi(
                srt(u()),
                pi(
                    quot_rel(),
                    pi(
                        srt(v()),
                        pi(
                            quot_lift_f(),
                            pi(
                                quot_lift_h(),
                                pi(
                                    ap2(cnst(bnm::quot_name(), vec![u()]), bv(4), bv(3)),
                                    bv(3),
                                ),
                            ),
                        ),
                    ),
                ),
            ),
        ),
        5,
        5,
        vec![rule(
            bnm::quot_mk_name(),
            1,
            lm(
                srt(u()),
                lm(
                    quot_rel(),
                    lm(
                        srt(v()),
                        lm(
                            quot_lift_f(),
                            lm(
                                quot_lift_h(),
                                lm(bv(4), expr::app(bv(2), bv(0))),
                            ),
                        ),
                    ),
                ),
            ),
        )],
    )
}

/// con-leche: ConLeche/Kernel/Basis/Quot.lean:74-77 quotIndMotive
/// `Quot.ind`'s motive slot, in the `α`/`r` context: `Quot α r → Prop`.
pub fn quot_ind_motive() -> Expr {
    pi(
        ap2(cnst(bnm::quot_name(), vec![u()]), bv(1), bv(0)),
        prop(),
    )
}

/// con-leche: ConLeche/Kernel/Basis/Quot.lean:79-83 quotIndMk
/// `Quot.ind`'s minor premise, in the `α`/`r`/`β` context:
/// `∀ a, β (Quot.mk α r a)`.
pub fn quot_ind_mk() -> Expr {
    pi(
        bv(2),
        expr::app(
            bv(1),
            ap3(cnst(bnm::quot_mk_name(), vec![u()]), bv(3), bv(2), bv(0)),
        ),
    )
}

/// con-leche: ConLeche/Kernel/Basis/Quot.lean:85-100 quotIndRaw
/// `Quot.ind.{u} {α : Sort u} {r : α → α → Prop} {β : Quot α r → Prop}
/// (mk : ∀ a, β (Quot.mk α r a)) (q : Quot α r) : β q`.
pub fn quot_ind_raw() -> ConstantInfo {
    ConstantInfo::RecInfo(
        cv(
            bnm::quot_ind_name(),
            vec![u_n()],
            pi(
                srt(u()),
                pi(
                    quot_rel(),
                    pi(
                        quot_ind_motive(),
                        pi(
                            quot_ind_mk(),
                            pi(
                                ap2(cnst(bnm::quot_name(), vec![u()]), bv(3), bv(2)),
                                expr::app(bv(2), bv(0)),
                            ),
                        ),
                    ),
                ),
            ),
        ),
        4,
        4,
        vec![rule(
            bnm::quot_mk_name(),
            1,
            lm(
                srt(u()),
                lm(
                    quot_rel(),
                    lm(
                        quot_ind_motive(),
                        lm(
                            quot_ind_mk(),
                            lm(bv(3), expr::app(bv(1), bv(0))),
                        ),
                    ),
                ),
            ),
        )],
    )
}

/// con-leche: ConLeche/Kernel/Basis/Quot.lean:102-114 quotSoundRaw
/// `Quot.sound.{u} {α : Sort u} {r : α → α → Prop} {a b : α} :
/// r a b → Quot.mk α r a = Quot.mk α r b`.
pub fn quot_sound_raw() -> ConstantInfo {
    ConstantInfo::AxiomInfo(cv(
        bnm::quot_sound_name(),
        vec![u_n()],
        pi(
            srt(u()),
            pi(
                quot_rel(),
                pi(
                    bv(1),
                    pi(
                        bv(2),
                        pi(
                            ap2(bv(2), bv(1), bv(0)),
                            ap3(
                                cnst(bnm::eq_name(), vec![u()]),
                                ap2(cnst(bnm::quot_name(), vec![u()]), bv(4), bv(3)),
                                ap3(cnst(bnm::quot_mk_name(), vec![u()]), bv(4), bv(3), bv(2)),
                                ap3(cnst(bnm::quot_mk_name(), vec![u()]), bv(4), bv(3), bv(1)),
                            ),
                        ),
                    ),
                ),
            ),
        ),
    ))
}

/// con-leche: ConLeche/Kernel/Basis/Quot.lean:116-118 quotBasis
/// The pinned `Quot` basis block, in install order.
pub fn quot_basis() -> Vec<ConstantInfo> {
    vec![
        quot_raw(),
        quot_mk_raw(),
        quot_lift_raw(),
        quot_ind_raw(),
        quot_sound_raw(),
    ]
}

/// con-leche: ConLeche/Kernel/Basis.lean:40-47 BasisKind.decls
/// The constants of one basis block, in dependency order.
pub fn basis_kind_decls(k: &BasisKind) -> Vec<ConstantInfo> {
    match k {
        BasisKind::EqK => eq_basis(),
        BasisKind::NatK => nat_basis(),
        BasisKind::PunitK => punit_basis(),
        BasisKind::EmptyK => empty_basis(),
        BasisKind::FalseK => false_basis(),
        BasisKind::QuotK => quot_basis(),
    }
}

/// con-leche: ConLeche/Kernel/Basis.lean:60-71 basisPinHit
/// The five blocks the pin match tries, as a list: con-leche writes the
/// literal `[BasisKind.eqK, .natK, .punitK, .emptyK, .falseK]` inline in
/// `basisPinHit`'s `List.find?`.  `quot` is not among them — its records
/// arrive one at a time and are matched slot by slot (`quot_pin_hit`).
pub fn block_pin_kinds() -> Vec<BasisKind> {
    vec![
        BasisKind::EqK,
        BasisKind::NatK,
        BasisKind::PunitK,
        BasisKind::EmptyK,
        BasisKind::FalseK,
    ]
}

/// con-leche: ConLeche/Kernel/Basis.lean:60-71 basisPinHit
/// **The basis-pin match**, with con-leche task #215's NAME pre-filter.
/// `ConstantInfo.canon` rebuilds the whole block as an unshared tree — on a
/// heavily DAG-shared block that was the frontend's single largest cost — so
/// a block that is not one of the five pinned ones must not reach it.  `canon`
/// renames only *level parameters*, leaving every constant name alone, so a
/// block can match a pin only when its members' names are the pin's, member
/// for member, and that test is a handful of `Name` comparisons.
///
/// The two phases stay in the cited order: `List.find?` picks the candidate
/// by NAMES, and only that one candidate is then `List.filter`ed by
/// `canonEqList`.  Deviation: the cited `find?`/`filter` closures are an
/// explicit index recursion (§3.4 forbids closures).
pub fn basis_pin_hit(block: &Vec<ConstantInfo>) -> Option<BasisKind> {
    let ks: Vec<BasisKind> = block_pin_kinds();
    basis_pin_hit_from(&ks, block, 0)
}

/// con-leche: ConLeche/Kernel/Basis.lean:60-71 basisPinHit
/// The index recursion behind `basis_pin_hit`: `ks[i..]`'s `find?` by name,
/// then the single `filter` by `canonEqList` on whatever it found.  A name
/// mismatch moves to the next kind; a name MATCH ends the search, and the
/// canonical comparison decides the result — exactly the cited
/// `(… .find? …).filter …`.
pub fn basis_pin_hit_from(
    ks: &Vec<BasisKind>,
    block: &Vec<ConstantInfo>,
    i: usize,
) -> Option<BasisKind> {
    if i >= ks.len() {
        None
    } else {
        let decls: Vec<ConstantInfo> = basis_kind_decls(&ks[i]);
        if !basis_pin_names_eq(&decls, block) {
            basis_pin_hit_from(ks, block, i + 1)
        } else if canon::canon_eq_list(block, &decls) {
            Some(env::basis_kind_dup(&ks[i]))
        } else {
            None
        }
    }
}

/// con-leche: ConLeche/Kernel/Basis.lean:60-71 basisPinHit
/// The pre-filter's test, `k.decls.map (·.name) == block.map (·.name)`.
pub fn basis_pin_names_eq(decls: &Vec<ConstantInfo>, block: &Vec<ConstantInfo>) -> bool {
    prop_when::names_beq(
        &env::constant_info_names_from(decls, 0, Vec::new()),
        &env::constant_info_names_from(block, 0, Vec::new()),
    )
}

/// con-leche: ConLeche/Kernel/Basis.lean:73-78 quotPinHit
/// `BasisKind.quotK.decls.getD slot (.axiomInfo default)`: the pinned
/// quotient package's constant at one slot, with the total-function fallback
/// the cited `getD` spells.  A separate function because `check_decl`'s
/// `Quot.sound` axiom arm reads slot 4 directly, as con-leche does.
///
/// Deviation: Lean's `default : ConstantVal` is the derived `Inhabited`
/// instance — `⟨.anonymous, [], .bvar 0⟩`, `Expr`'s own default being its
/// first constructor.  The fallback is unreachable: `quot_basis` has exactly
/// the five members `quot_kind_slot` indexes.
pub fn quot_basis_at(slot: u64) -> ConstantInfo {
    let decls: Vec<ConstantInfo> = quot_basis();
    if slot < decls.len() as u64 {
        env::constant_info_dup(&decls[slot as usize])
    } else {
        ConstantInfo::AxiomInfo(cv(name::anonymous(), Vec::new(), expr::bvar(0)))
    }
}

/// con-leche: ConLeche/Kernel/Basis.lean:73-78 quotPinHit
/// **The quotient-pin match**: the record is the pinned package's constant at
/// the slot it declares itself at.  The two are compared at `toConstantVal`,
/// which con-leche's `ConstantInfo.canon_toConstantVal` identifies with
/// `ConstantVal.canon` of each side — so the port compares the two
/// `ConstantVal`s with `canon::constant_val_canon_eq`, the lockstep twin of
/// the cited `ConstantVal.canonEq`.
pub fn quot_pin_hit(k: &QuotKind, cv: &ConstantVal) -> bool {
    canon::constant_val_canon_eq(cv, &env::to_constant_val(&quot_basis_at(env::quot_kind_slot(k))))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::kernel::basis_tables;

    /// The raw pins and the *annotated* tables of `con-ron-core` are the same
    /// blocks up to the annotation — which is exactly what
    /// `ConstantInfo.canon` erases (binder metadata, `IndCaps`) and what it
    /// does NOT (a recursor rule's install-computed fields).  So the module
    /// note's claim is testable both ways: every block has the pin's member
    /// NAMES in the pin's order (the task-#215 pre-filter), and the
    /// `canonEq` comparison of the raw block against the annotated one FAILS
    /// wherever the annotation moved a rule field — which is why the raw pins
    /// have to exist.
    #[test]
    fn raw_pins_have_the_annotated_blocks_names_but_not_their_rules() {
        let kinds = [
            BasisKind::EqK,
            BasisKind::NatK,
            BasisKind::PunitK,
            BasisKind::EmptyK,
            BasisKind::FalseK,
            BasisKind::QuotK,
        ];
        let mut differed = 0;
        for k in kinds.iter() {
            let raw = basis_kind_decls(k);
            let ann = basis_tables::basis_decls_a(k);
            assert_eq!(raw.len(), ann.len());
            for (r, a) in raw.iter().zip(ann.iter()) {
                assert!(
                    name::beq(&env::constant_info_name(r), &env::constant_info_name(a)),
                    "member names differ"
                );
            }
            if !canon::canon_eq_list(&raw, &ann) {
                differed += 1;
            }
        }
        // `Eq`, `Nat`, `PUnit` and `Quot` carry iota rules whose
        // install-computed fields the annotation fills in; `Empty` and
        // `False` have no rules at all and compare equal.
        assert_eq!(differed, 4);
    }

    /// A raw block matches itself up to the canonical form, which is the
    /// property the pin match relies on.
    #[test]
    fn raw_pins_match_themselves() {
        for k in [
            BasisKind::EqK,
            BasisKind::NatK,
            BasisKind::PunitK,
            BasisKind::EmptyK,
            BasisKind::FalseK,
            BasisKind::QuotK,
        ] {
            assert!(canon::canon_eq_list(
                &basis_kind_decls(&k),
                &basis_kind_decls(&k)
            ));
        }
    }

    fn kind_ix(k: &BasisKind) -> u64 {
        match k {
            BasisKind::EqK => 0,
            BasisKind::NatK => 1,
            BasisKind::PunitK => 2,
            BasisKind::EmptyK => 3,
            BasisKind::FalseK => 4,
            BasisKind::QuotK => 5,
        }
    }

    /// The fold's block test: each of the five pins is recognised as itself,
    /// the annotated block is NOT (its recursor rules carry the
    /// install-computed fields the parse cannot know), and a block under none
    /// of the five names never reaches the canonical comparison at all.
    #[test]
    fn basis_pin_hit_recognises_the_five_and_nothing_else() {
        for k in block_pin_kinds() {
            match basis_pin_hit(&basis_kind_decls(&k)) {
                Some(hit) => assert_eq!(kind_ix(&hit), kind_ix(&k)),
                None => panic!("pin not recognised"),
            }
        }
        // the annotated `Nat` block has the pin's NAMES but not its rules
        let ann = basis_tables::basis_decls_a(&BasisKind::NatK);
        assert!(basis_pin_names_eq(&basis_kind_decls(&BasisKind::NatK), &ann));
        assert!(basis_pin_hit(&ann).is_none());
        // a block whose members are nobody's pin: the name pre-filter refuses
        // it, so `canon_eq_list` is never reached
        let stranger = vec![ConstantInfo::AxiomInfo(cv(
            bnm::list_name(),
            Vec::new(),
            srt(u()),
        ))];
        assert!(!basis_pin_names_eq(
            &basis_kind_decls(&BasisKind::EqK),
            &stranger
        ));
        assert!(basis_pin_hit(&stranger).is_none());
        // `quot` is not a block pin: its records arrive one at a time
        assert!(basis_pin_hit(&quot_basis()).is_none());
    }

    /// The fold's quotient test: each of the five slots matches its own pin
    /// and no other.
    #[test]
    fn quot_pin_hit_matches_its_own_slot() {
        let kinds = [
            QuotKind::Type,
            QuotKind::Ctor,
            QuotKind::Lift,
            QuotKind::Ind,
            QuotKind::Sound,
        ];
        for k in kinds.iter() {
            let own = env::to_constant_val(&quot_basis_at(env::quot_kind_slot(k)));
            assert!(quot_pin_hit(k, &own));
            for k2 in kinds.iter() {
                if env::quot_kind_slot(k) != env::quot_kind_slot(k2) {
                    assert!(!quot_pin_hit(k2, &own));
                }
            }
        }
        // slot 4 is `Quot.sound`, which `check_decl`'s axiom arm reads directly
        assert!(name::beq(
            &env::constant_info_name(&quot_basis_at(4)),
            &bnm::quot_sound_name()
        ));
        // the out-of-range fallback is the anonymous placeholder axiom
        assert!(name::beq(
            &env::constant_info_name(&quot_basis_at(5)),
            &name::anonymous()
        ));
    }
}
