//! `ConLeche/Kernel/NatOpPinSet.lean` and `ConLeche/Kernel/NatOpPins.lean` —
//! one toolchain's `Nat`-operation pins, and the list of committed variants.
//!
//! A **pin variant** carries, per pin-certified WF-recursive `Nat` operation
//! (`Nat.div`, `Nat.mod`, `gcd`, `land`, `lor`, `xor`, `shiftLeft`,
//! `shiftRight`), that toolchain's pinned defining expression and its
//! certificate proof blobs.  The install gate
//! (`checker::check_div_mod_pin_loop`) tries the variants in order and
//! enables the operation's literal fast path on the first whose guards pass,
//! whose pin is definitionally equal to the stream's stored value and whose
//! certificates check.  The certificate *statements* the proofs are checked
//! against are hand-pinned in `checker::div_mod_cert_stmts` and shared by
//! every variant.
//!
//! **Two Lean files, one Rust module.**  `NatOpPinSet.lean` is the record and
//! `NatOpPins.lean` the generated list; the list is meaningless without the
//! record and the record has no other consumer, so they share a module
//! (DESIGN.md §3.1's one-module-per-file rule bent once, recorded here).
//!
//! **`nat_op_pin_sets` is a stub.**  In con-leche the list is *spliced* from
//! the committed `pins/*.json` dumps by an elaboration-time command
//! (`#load_natop_pins`); porting it means generating a table of `Expr` blobs,
//! which is task #22's job.  Until then it is empty, which is a-priori safe:
//! `checkDivModPinLoop` on an empty variant list is its `[]` arm, i.e. the
//! decline con-leche itself gives a stream matching no variant ("unsupported
//! Nat.div/mod spelling"), so the loop is exercised with zero pins and the
//! only effect is that `Nat.div`/`Nat.mod` streams decline — sound for the
//! accept direction (DESIGN.md §1).

use crate::kernel::expr::Expr;
use std::vec::Vec;

/// con-leche: ConLeche/Kernel/NatOpPinSet.lean:26-49 NatOpPinSet
/// The pins of one toolchain: eight pinned defining expressions and eight
/// certificate-proof lists, in the order of `natDivModNames`' family, plus
/// the toolchain string for diagnostics.  Deviation: `toolchain : String` is
/// a `Vec<u32>` of code points (DESIGN.md §3.3).
pub struct NatOpPinSet {
    pub toolchain: Vec<u32>,
    pub div_pin: Expr,
    pub mod_pin: Expr,
    pub gcd_pin: Expr,
    pub land_pin: Expr,
    pub lor_pin: Expr,
    pub xor_pin: Expr,
    pub shift_left_pin: Expr,
    pub shift_right_pin: Expr,
    pub div_proofs: Vec<Expr>,
    pub mod_proofs: Vec<Expr>,
    pub gcd_proofs: Vec<Expr>,
    pub land_proofs: Vec<Expr>,
    pub lor_proofs: Vec<Expr>,
    pub xor_proofs: Vec<Expr>,
    pub shift_left_proofs: Vec<Expr>,
    pub shift_right_proofs: Vec<Expr>,
}

/// con-leche: ConLeche/Kernel/NatOpPins.lean:61-64 _
/// The committed pin variants, in the order the install gate tries them
/// (the repository's own toolchain first).
///
/// **Stub**: the table is generated by task #22 (see the module note); the
/// empty list makes `check_div_mod_pin_loop` take its `[]` arm and decline,
/// as con-leche does for a stream matching no variant.
pub fn nat_op_pin_sets() -> Vec<NatOpPinSet> {
    Vec::new()
}
