//! `ConLeche/Kernel/Basis/{Eq,Nat,PUnit,Empty,False,Quot}.lean` and
//! `ConLeche/Kernel/Basis.lean` — the **raw** pinned basis blocks: each block
//! exactly as an export carries it, the toolchain's `Init.Prelude`
//! declaration at the parser's raw binder annotations.
//!
//! **Why they are in the frontend crate.**  con-ron-core carries the
//! *annotated* blocks (`kernel::basis_tables`, `BasisKind.declsA`,
//! generated by task #22), which is what the installation stores; the raw
//! pins are what the FRONTEND matches an incoming record against
//! (`export_c::process_line_core_d`'s five-pin block match and its two
//! quotient comparisons), and nothing below `check_decls` reads them.  They
//! could not be borrowed from `basis_tables`: `canonEq` resets binder
//! metadata and `IndCaps` on both sides but compares a recursor rule's
//! install-computed fields (`ctorParams`, `fire`, `k`, `eta`, `paramsBlind`)
//! verbatim, and the annotated `Nat.rec` rule carries `ctorParams = 2`,
//! `fire = .plain`, `k = true`, `paramsBlind = true` where a parsed one
//! carries the placeholders.  A stream's `Nat` block would then never match
//! the pin, which is a verdict divergence, not a cosmetic one.
//!
//! con-leche's own module split is the same one for the same reason:
//! `Kernel/Basis.lean` (the raw pins) sits BELOW `Kernel/TypeChecker`
//! because "the kernel core needs the raw pins (the frontend matches incoming
//! records against them) and nothing else", and `Kernel/BasisA.lean` sits
//! above it.  Should a later task need the raw pins inside the verified core,
//! this module moves there unchanged.
//!
//! Written with con-ron-core's port of the raw-pin DSL
//! (`kernel::basis_builder`, task #18), so a reader can line each pin up
//! against `Init.Prelude` binder by binder exactly as in the Lean.  The
//! DSL's own deviation stands: `pi`/`piI`/`piA` are one function and
//! `lm`/`lmI` are one, because `Expr` carries neither a binder name nor a
//! binder info.

use con_ron_core::kernel::basis_builder::{ap2, ap3, bn, bv, cnst, lm, pi, prop, srt, type1, u, u1};
use con_ron_core::kernel::basis_builder::{u1_n, u_n, v, v_n};
use con_ron_core::kernel::basis_names as bnm;
use con_ron_core::kernel::env;
use con_ron_core::kernel::env::{BasisKind, ConstantInfo, ConstantVal, IndCaps, RecRule};
use con_ron_core::kernel::expr::Expr;
use con_ron_core::kernel::name;
use con_ron_core::kernel::name::Name;
use con_ron_core::kernel::prop_when;

/// con-leche: none — the code-point spelling of a `String` literal (DESIGN.md
/// §3.3); con-leche writes the `String` itself.
pub fn cps(s: &str) -> Vec<u32> {
    s.chars().map(|c| c as u32).collect()
}

/// con-leche: none — `ConstantVal.mk` at the anonymous-constructor literal
/// `⟨name, lps, ty⟩` every pin below opens with.
pub fn cv(n: Name, lps: Vec<Name>, ty: Expr) -> ConstantVal {
    ConstantVal {
        name: n,
        level_params: lps,
        ty,
    }
}

/// con-leche: ConLeche/Kernel/Basis/Builder.lean:117-121 BasisDSL.rule
/// A raw iota rule: the install-computed fields (`ctorParams`, `fire`, `k`,
/// `eta`, `paramsBlind`) at their parse placeholders, which is what the
/// exporter emits and what `#annotate_basis` recomputes.
pub fn rule(ctor: Name, nfields: u64, rhs: Expr) -> RecRule {
    env::rec_rule_parsed(ctor, nfields, rhs)
}

// --- Eq --------------------------------------------------------------------

/// con-leche: ConLeche/Kernel/Basis/Eq.lean:22-28 eqRaw
/// `Eq.{u} {α : Sort u} : α → α → Prop`.
pub fn eq_raw() -> ConstantInfo {
    let caps = IndCaps {
        rule_k: true,
        ..env::ind_caps_default()
    };
    ConstantInfo::IndInfo(
        cv(
            bnm::eq_name(),
            vec![u_n()],
            pi(srt(u()), pi(bv(0), pi(bv(1), prop()))),
        ),
        caps,
    )
}

/// con-leche: ConLeche/Kernel/Basis/Eq.lean:30-36 eqReflRaw
/// `Eq.refl.{u} {α : Sort u} (a : α) : Eq α a a`.
pub fn eq_refl_raw() -> ConstantInfo {
    ConstantInfo::CtorInfo(
        cv(
            bnm::eq_refl_name(),
            vec![u_n()],
            pi(
                srt(u()),
                pi(
                    bv(0),
                    ap3(cnst(bnm::eq_name(), vec![u()]), bv(1), bv(0), bv(0)),
                ),
            ),
        ),
        2,
        0,
    )
}

/// con-leche: ConLeche/Kernel/Basis/Eq.lean:38-42 eqRecMotive
/// The motive of `Eq.rec`: `∀ (b : α) (t : Eq α a b), Sort u_1`, in the
/// `α`/`a` binder context (`α` is `#1`, `a` is `#0` at its head).
pub fn eq_rec_motive() -> Expr {
    pi(
        bv(1),
        pi(
            ap3(cnst(bnm::eq_name(), vec![u()]), bv(2), bv(1), bv(0)),
            srt(u1()),
        ),
    )
}

/// con-leche: none — `Eq.rec`'s `refl` minor premise, `motive a (Eq.refl α
/// a)`, which `eqRecRaw` spells twice (in its type and in its iota rule).
pub fn eq_rec_refl_dom() -> Expr {
    ap2(
        bv(0),
        bv(1),
        ap2(cnst(bnm::eq_refl_name(), vec![u()]), bv(2), bv(1)),
    )
}

/// con-leche: ConLeche/Kernel/Basis/Eq.lean:44-61 eqRecRaw
/// `Eq.rec.{u_1, u} {α : Sort u} {a : α} {motive : ∀ b, Eq α a b → Sort u_1}
/// (refl : motive a (Eq.refl α a)) {b : α} (t : Eq α a b) : motive b t`.
pub fn eq_rec_raw() -> ConstantInfo {
    ConstantInfo::RecInfo(
        cv(
            name::mk_str(bnm::eq_name(), cps("rec")),
            vec![u1_n(), u_n()],
            pi(
                srt(u()),
                pi(
                    bv(0),
                    pi(
                        eq_rec_motive(),
                        pi(
                            eq_rec_refl_dom(),
                            pi(
                                bv(3),
                                pi(
                                    ap3(cnst(bnm::eq_name(), vec![u()]), bv(4), bv(3), bv(0)),
                                    ap2(bv(3), bv(1), bv(0)),
                                ),
                            ),
                        ),
                    ),
                ),
            ),
        ),
        5,
        4,
        vec![rule(
            bnm::eq_refl_name(),
            0,
            lm(
                srt(u()),
                lm(
                    bv(0),
                    lm(eq_rec_motive(), lm(eq_rec_refl_dom(), bv(0))),
                ),
            ),
        )],
    )
}

/// con-leche: ConLeche/Kernel/Basis/Eq.lean:63-64 eqBasis
/// The pinned `Eq` basis block, in install order.
pub fn eq_basis() -> Vec<ConstantInfo> {
    vec![eq_raw(), eq_refl_raw(), eq_rec_raw()]
}

// --- Nat -------------------------------------------------------------------

/// con-leche: ConLeche/Kernel/Basis/Nat.lean:21-22 natT
/// The type `Nat`, as a closed constant.
pub fn nat_t() -> Expr {
    cnst(bnm::nat_name(), Vec::new())
}

/// con-leche: ConLeche/Kernel/Basis/Nat.lean:24-26 natRaw
/// `Nat : Type`.
pub fn nat_raw() -> ConstantInfo {
    ConstantInfo::IndInfo(
        cv(bnm::nat_name(), Vec::new(), type1()),
        env::ind_caps_default(),
    )
}

/// con-leche: ConLeche/Kernel/Basis/Nat.lean:28-30 natZeroRaw
/// `Nat.zero : Nat`.
pub fn nat_zero_raw() -> ConstantInfo {
    ConstantInfo::CtorInfo(cv(bnm::nat_zero_name(), Vec::new(), nat_t()), 0, 0)
}

/// con-leche: ConLeche/Kernel/Basis/Nat.lean:32-34 natSuccRaw
/// `Nat.succ (n : Nat) : Nat`.
pub fn nat_succ_raw() -> ConstantInfo {
    ConstantInfo::CtorInfo(
        cv(bnm::nat_succ_name(), Vec::new(), pi(nat_t(), nat_t())),
        0,
        1,
    )
}

/// con-leche: ConLeche/Kernel/Basis/Nat.lean:36-37 natRecMotive
/// The motive of `Nat.rec`: `∀ (t : Nat), Sort u`.
pub fn nat_rec_motive() -> Expr {
    pi(nat_t(), srt(u()))
}

/// con-leche: ConLeche/Kernel/Basis/Nat.lean:39-44 natRecSucc
/// The successor minor premise of `Nat.rec`, in the `motive`/`zero` binder
/// context: `∀ (n : Nat), motive n → motive (Nat.succ n)`.
pub fn nat_rec_succ() -> Expr {
    pi(
        nat_t(),
        pi(
            con_ron_core::kernel::expr::app(bv(2), bv(0)),
            con_ron_core::kernel::expr::app(
                bv(3),
                con_ron_core::kernel::expr::app(cnst(bnm::nat_succ_name(), Vec::new()), bv(1)),
            ),
        ),
    )
}

/// con-leche: none — `Nat.rec`'s `zero` minor premise, `motive Nat.zero`,
/// which `natRecRaw` spells three times (its type and both iota rules).
pub fn nat_rec_zero_dom() -> Expr {
    con_ron_core::kernel::expr::app(bv(0), cnst(bnm::nat_zero_name(), Vec::new()))
}

/// con-leche: ConLeche/Kernel/Basis/Nat.lean:46-65 natRecRaw
/// `Nat.rec.{u} {motive : Nat → Sort u} (zero : motive Nat.zero)
/// (succ : ∀ n, motive n → motive n.succ) (t : Nat) : motive t`.
pub fn nat_rec_raw() -> ConstantInfo {
    let rec_name = name::mk_str(bnm::nat_name(), cps("rec"));
    ConstantInfo::RecInfo(
        cv(
            name::dup(&rec_name),
            vec![u_n()],
            pi(
                nat_rec_motive(),
                pi(
                    nat_rec_zero_dom(),
                    pi(
                        nat_rec_succ(),
                        pi(nat_t(), con_ron_core::kernel::expr::app(bv(3), bv(0))),
                    ),
                ),
            ),
        ),
        3,
        3,
        vec![
            rule(
                bnm::nat_zero_name(),
                0,
                lm(
                    nat_rec_motive(),
                    lm(nat_rec_zero_dom(), lm(nat_rec_succ(), bv(1))),
                ),
            ),
            rule(
                bnm::nat_succ_name(),
                1,
                lm(
                    nat_rec_motive(),
                    lm(
                        nat_rec_zero_dom(),
                        lm(
                            nat_rec_succ(),
                            lm(
                                nat_t(),
                                ap2(
                                    bv(1),
                                    bv(0),
                                    con_ron_core::kernel::expr::app(
                                        ap3(
                                            cnst(name::dup(&rec_name), vec![u()]),
                                            bv(3),
                                            bv(2),
                                            bv(1),
                                        ),
                                        bv(0),
                                    ),
                                ),
                            ),
                        ),
                    ),
                ),
            ),
        ],
    )
}

/// con-leche: ConLeche/Kernel/Basis/Nat.lean:67-68 natBasis
/// The pinned `Nat` basis block, in install order.
pub fn nat_basis() -> Vec<ConstantInfo> {
    vec![nat_raw(), nat_zero_raw(), nat_succ_raw(), nat_rec_raw()]
}

// --- PUnit -----------------------------------------------------------------

/// con-leche: ConLeche/Kernel/Basis/PUnit.lean:24-29 punitRaw
/// `PUnit.{u} : Sort u`.
pub fn punit_raw() -> ConstantInfo {
    let caps = IndCaps {
        eta: true,
        eta_ctor: bnm::punit_unit_name(),
        eta_params: 0,
        eta_fields: 0,
        unitlike: true,
        sort_z: prop_when::if_all_zero(vec![u_n()]),
        ..env::ind_caps_default()
    };
    ConstantInfo::IndInfo(cv(bnm::punit_name(), vec![u_n()], srt(u())), caps)
}

/// con-leche: ConLeche/Kernel/Basis/PUnit.lean:31-33 punitUnitRaw
/// `PUnit.unit.{u} : PUnit.{u}`.
pub fn punit_unit_raw() -> ConstantInfo {
    ConstantInfo::CtorInfo(
        cv(
            bnm::punit_unit_name(),
            vec![u_n()],
            cnst(bnm::punit_name(), vec![u()]),
        ),
        0,
        0,
    )
}

/// con-leche: ConLeche/Kernel/Basis/PUnit.lean:35-37 punitRecMotive
/// The motive of `PUnit.rec`: `∀ (t : PUnit.{u}), Sort u_1`.
pub fn punit_rec_motive() -> Expr {
    pi(cnst(bnm::punit_name(), vec![u()]), srt(u1()))
}

/// con-leche: none — `PUnit.rec`'s `unit` minor premise, `motive PUnit.unit`,
/// which `punitRecRaw` spells twice (its type and its iota rule).
pub fn punit_rec_unit_dom() -> Expr {
    con_ron_core::kernel::expr::app(bv(0), cnst(bnm::punit_unit_name(), vec![u()]))
}

/// con-leche: ConLeche/Kernel/Basis/PUnit.lean:39-50 punitRecRaw
/// `PUnit.rec.{u_1, u} {motive : PUnit.{u} → Sort u_1} (unit : motive
/// PUnit.unit) (t : PUnit.{u}) : motive t`.
pub fn punit_rec_raw() -> ConstantInfo {
    ConstantInfo::RecInfo(
        cv(
            bnm::punit_rec_name(),
            vec![u1_n(), u_n()],
            pi(
                punit_rec_motive(),
                pi(
                    punit_rec_unit_dom(),
                    pi(
                        cnst(bnm::punit_name(), vec![u()]),
                        con_ron_core::kernel::expr::app(bv(2), bv(0)),
                    ),
                ),
            ),
        ),
        2,
        2,
        vec![rule(
            bnm::punit_unit_name(),
            0,
            lm(punit_rec_motive(), lm(punit_rec_unit_dom(), bv(0))),
        )],
    )
}

/// con-leche: ConLeche/Kernel/Basis/PUnit.lean:52-53 punitBasis
/// The pinned `PUnit` basis block, in install order.
pub fn punit_basis() -> Vec<ConstantInfo> {
    vec![punit_raw(), punit_unit_raw(), punit_rec_raw()]
}

// --- Empty -----------------------------------------------------------------

/// con-leche: ConLeche/Kernel/Basis/Empty.lean:21-23 emptyRaw
/// `Empty : Type`.
pub fn empty_raw() -> ConstantInfo {
    ConstantInfo::IndInfo(
        cv(bnm::empty_name(), Vec::new(), type1()),
        env::ind_caps_default(),
    )
}

/// con-leche: ConLeche/Kernel/Basis/Empty.lean:25-32 emptyRecRaw
/// `Empty.rec.{u} (motive : Empty → Sort u) (t : Empty) : motive t`.  The
/// exporter emits the motive as an *explicit* binder here (there is no major
/// premise to infer it from).
pub fn empty_rec_raw() -> ConstantInfo {
    ConstantInfo::RecInfo(
        cv(
            name::mk_str(bnm::empty_name(), cps("rec")),
            vec![u_n()],
            pi(
                pi(cnst(bnm::empty_name(), Vec::new()), srt(u())),
                pi(
                    cnst(bnm::empty_name(), Vec::new()),
                    con_ron_core::kernel::expr::app(bv(1), bv(0)),
                ),
            ),
        ),
        1,
        1,
        Vec::new(),
    )
}

/// con-leche: ConLeche/Kernel/Basis/Empty.lean:34-35 emptyBasis
/// The pinned `Empty` basis block, in install order.
pub fn empty_basis() -> Vec<ConstantInfo> {
    vec![empty_raw(), empty_rec_raw()]
}

// --- False -----------------------------------------------------------------

/// con-leche: ConLeche/Kernel/Basis/False.lean:38-40 falseRaw
/// `False : Prop`.
pub fn false_raw() -> ConstantInfo {
    ConstantInfo::IndInfo(
        cv(bnm::false_name(), Vec::new(), prop()),
        env::ind_caps_default(),
    )
}

/// con-leche: ConLeche/Kernel/Basis/False.lean:42-49 falseRecRaw
/// `False.rec.{u} (motive : False → Sort u) (t : False) : motive t`.  The
/// exporter emits the motive as an *explicit* binder here, as for
/// `Empty.rec`.
pub fn false_rec_raw() -> ConstantInfo {
    ConstantInfo::RecInfo(
        cv(
            name::mk_str(bnm::false_name(), cps("rec")),
            vec![u_n()],
            pi(
                pi(cnst(bnm::false_name(), Vec::new()), srt(u())),
                pi(
                    cnst(bnm::false_name(), Vec::new()),
                    con_ron_core::kernel::expr::app(bv(1), bv(0)),
                ),
            ),
        ),
        1,
        1,
        Vec::new(),
    )
}

/// con-leche: ConLeche/Kernel/Basis/False.lean:51-52 falseBasis
/// The pinned `False` basis block, in install order.
pub fn false_basis() -> Vec<ConstantInfo> {
    vec![false_raw(), false_rec_raw()]
}

// --- Quot ------------------------------------------------------------------

/// con-leche: ConLeche/Kernel/Basis/Quot.lean:26-28 quotRel
/// The relation argument's type in the `α` binder context: `α → α → Prop`.
pub fn quot_rel() -> Expr {
    pi(bv(0), pi(bv(1), prop()))
}

/// con-leche: ConLeche/Kernel/Basis/Quot.lean:30-34 quotRaw
/// `Quot.{u} {α : Sort u} (r : α → α → Prop) : Sort u`.
pub fn quot_raw() -> ConstantInfo {
    ConstantInfo::IndInfo(
        cv(
            bnm::quot_name(),
            vec![u_n()],
            pi(srt(u()), pi(quot_rel(), srt(u()))),
        ),
        env::ind_caps_default(),
    )
}

/// con-leche: ConLeche/Kernel/Basis/Quot.lean:36-42 quotMkRaw
/// `Quot.mk.{u} {α : Sort u} (r : α → α → Prop) (a : α) : Quot α r`.
pub fn quot_mk_raw() -> ConstantInfo {
    ConstantInfo::CtorInfo(
        cv(
            bnm::quot_mk_name(),
            vec![u_n()],
            pi(
                srt(u()),
                pi(
                    quot_rel(),
                    pi(
                        bv(1),
                        ap2(cnst(bnm::quot_name(), vec![u()]), bv(2), bv(1)),
                    ),
                ),
            ),
        ),
        2,
        1,
    )
}

/// con-leche: ConLeche/Kernel/Basis/Quot.lean:44-45 quotLiftF
/// `Quot.lift`'s function slot, in the `α`/`r`/`β` context: `α → β`.
pub fn quot_lift_f() -> Expr {
    pi(bv(2), bv(1))
}

/// con-leche: ConLeche/Kernel/Basis/Quot.lean:47-53 quotLiftH
/// `Quot.lift`'s coherence slot, in the `α`/`r`/`β`/`f` context:
/// `∀ a b, r a b → f a = f b`.
pub fn quot_lift_h() -> Expr {
    pi(
        bv(3),
        pi(
            bv(4),
            pi(
                ap2(bv(4), bv(1), bv(0)),
                ap3(
                    cnst(bnm::eq_name(), vec![v()]),
                    bv(4),
                    con_ron_core::kernel::expr::app(bv(3), bv(2)),
                    con_ron_core::kernel::expr::app(bv(3), bv(1)),
                ),
            ),
        ),
    )
}

/// con-leche: ConLeche/Kernel/Basis/Quot.lean:55-72 quotLiftRaw
/// `Quot.lift.{u, v} {α : Sort u} {r : α → α → Prop} {β : Sort v}
/// (f : α → β) (h : ∀ a b, r a b → f a = f b) (q : Quot α r) : β`.
pub fn quot_lift_raw() -> ConstantInfo {
    ConstantInfo::RecInfo(
        cv(
            bnm::quot_lift_name(),
            vec![u_n(), v_n()],
            pi(
                srt(u()),
                pi(
                    quot_rel(),
                    pi(
                        srt(v()),
                        pi(
                            quot_lift_f(),
                            pi(
                                quot_lift_h(),
                                pi(
                                    ap2(cnst(bnm::quot_name(), vec![u()]), bv(4), bv(3)),
                                    bv(3),
                                ),
                            ),
                        ),
                    ),
                ),
            ),
        ),
        5,
        5,
        vec![rule(
            bnm::quot_mk_name(),
            1,
            lm(
                srt(u()),
                lm(
                    quot_rel(),
                    lm(
                        srt(v()),
                        lm(
                            quot_lift_f(),
                            lm(
                                quot_lift_h(),
                                lm(bv(4), con_ron_core::kernel::expr::app(bv(2), bv(0))),
                            ),
                        ),
                    ),
                ),
            ),
        )],
    )
}

/// con-leche: ConLeche/Kernel/Basis/Quot.lean:74-77 quotIndMotive
/// `Quot.ind`'s motive slot, in the `α`/`r` context: `Quot α r → Prop`.
pub fn quot_ind_motive() -> Expr {
    pi(
        ap2(cnst(bnm::quot_name(), vec![u()]), bv(1), bv(0)),
        prop(),
    )
}

/// con-leche: ConLeche/Kernel/Basis/Quot.lean:79-83 quotIndMk
/// `Quot.ind`'s minor premise, in the `α`/`r`/`β` context:
/// `∀ a, β (Quot.mk α r a)`.
pub fn quot_ind_mk() -> Expr {
    pi(
        bv(2),
        con_ron_core::kernel::expr::app(
            bv(1),
            ap3(cnst(bnm::quot_mk_name(), vec![u()]), bv(3), bv(2), bv(0)),
        ),
    )
}

/// con-leche: ConLeche/Kernel/Basis/Quot.lean:85-100 quotIndRaw
/// `Quot.ind.{u} {α : Sort u} {r : α → α → Prop} {β : Quot α r → Prop}
/// (mk : ∀ a, β (Quot.mk α r a)) (q : Quot α r) : β q`.
pub fn quot_ind_raw() -> ConstantInfo {
    ConstantInfo::RecInfo(
        cv(
            bnm::quot_ind_name(),
            vec![u_n()],
            pi(
                srt(u()),
                pi(
                    quot_rel(),
                    pi(
                        quot_ind_motive(),
                        pi(
                            quot_ind_mk(),
                            pi(
                                ap2(cnst(bnm::quot_name(), vec![u()]), bv(3), bv(2)),
                                con_ron_core::kernel::expr::app(bv(2), bv(0)),
                            ),
                        ),
                    ),
                ),
            ),
        ),
        4,
        4,
        vec![rule(
            bnm::quot_mk_name(),
            1,
            lm(
                srt(u()),
                lm(
                    quot_rel(),
                    lm(
                        quot_ind_motive(),
                        lm(
                            quot_ind_mk(),
                            lm(bv(3), con_ron_core::kernel::expr::app(bv(1), bv(0))),
                        ),
                    ),
                ),
            ),
        )],
    )
}

/// con-leche: ConLeche/Kernel/Basis/Quot.lean:102-114 quotSoundRaw
/// `Quot.sound.{u} {α : Sort u} {r : α → α → Prop} {a b : α} :
/// r a b → Quot.mk α r a = Quot.mk α r b`.
pub fn quot_sound_raw() -> ConstantInfo {
    ConstantInfo::AxiomInfo(cv(
        bnm::quot_sound_name(),
        vec![u_n()],
        pi(
            srt(u()),
            pi(
                quot_rel(),
                pi(
                    bv(1),
                    pi(
                        bv(2),
                        pi(
                            ap2(bv(2), bv(1), bv(0)),
                            ap3(
                                cnst(bnm::eq_name(), vec![u()]),
                                ap2(cnst(bnm::quot_name(), vec![u()]), bv(4), bv(3)),
                                ap3(cnst(bnm::quot_mk_name(), vec![u()]), bv(4), bv(3), bv(2)),
                                ap3(cnst(bnm::quot_mk_name(), vec![u()]), bv(4), bv(3), bv(1)),
                            ),
                        ),
                    ),
                ),
            ),
        ),
    ))
}

/// con-leche: ConLeche/Kernel/Basis/Quot.lean:116-118 quotBasis
/// The pinned `Quot` basis block, in install order.
pub fn quot_basis() -> Vec<ConstantInfo> {
    vec![
        quot_raw(),
        quot_mk_raw(),
        quot_lift_raw(),
        quot_ind_raw(),
        quot_sound_raw(),
    ]
}

/// con-leche: ConLeche/Kernel/Basis.lean:39-46 BasisKind.decls
/// The constants of one basis block, in dependency order.
pub fn basis_decls(k: &BasisKind) -> Vec<ConstantInfo> {
    match k {
        BasisKind::EqK => eq_basis(),
        BasisKind::NatK => nat_basis(),
        BasisKind::PunitK => punit_basis(),
        BasisKind::EmptyK => empty_basis(),
        BasisKind::FalseK => false_basis(),
        BasisKind::QuotK => quot_basis(),
    }
}

/// con-leche: none — the five blocks `ExportC.lean`'s pin match tries, as a
/// list (con-leche writes the literal `[BasisKind.eqK, .natK, .punitK,
/// .emptyK, .falseK]` inline in `processLineCoreD`).  `quot` is not among
/// them: its records arrive one at a time and are matched slot by slot.
pub fn block_pin_kinds() -> Vec<BasisKind> {
    vec![
        BasisKind::EqK,
        BasisKind::NatK,
        BasisKind::PunitK,
        BasisKind::EmptyK,
        BasisKind::FalseK,
    ]
}

/// con-leche: none — the unused `basis_builder` re-export the DSL needs for
/// `bn`; kept so the module's one hand-written name (`"rec"`) and the DSL's
/// own name helpers come from the same place.
pub fn dsl_bn(s: &str) -> Name {
    bn(cps(s))
}

#[cfg(test)]
mod tests {
    use super::*;
    use con_ron_core::kernel::basis_tables;

    /// The raw pins and the *annotated* tables of `con-ron-core` are the same
    /// blocks up to the annotation — which is exactly what
    /// `ConstantInfo.canon` erases (binder metadata, `IndCaps`) and what it
    /// does NOT (a recursor rule's install-computed fields).  So the module
    /// note's claim is testable both ways: every block has the pin's member
    /// NAMES in the pin's order (the task-#215 pre-filter), and the
    /// `canonEq` comparison of the raw block against the annotated one FAILS
    /// wherever the annotation moved a rule field — which is why the raw pins
    /// have to exist.
    #[test]
    fn raw_pins_have_the_annotated_blocks_names_but_not_their_rules() {
        let kinds = [
            BasisKind::EqK,
            BasisKind::NatK,
            BasisKind::PunitK,
            BasisKind::EmptyK,
            BasisKind::FalseK,
            BasisKind::QuotK,
        ];
        let mut differed = 0;
        for k in kinds.iter() {
            let raw = basis_decls(k);
            let ann = basis_tables::basis_decls_a(k);
            assert_eq!(raw.len(), ann.len());
            for (r, a) in raw.iter().zip(ann.iter()) {
                assert!(
                    name::beq(&env::constant_info_name(r), &env::constant_info_name(a)),
                    "member names differ"
                );
            }
            if !crate::frontend::export::canon_eq_list(&raw, &ann) {
                differed += 1;
            }
        }
        // `Eq`, `Nat`, `PUnit` and `Quot` carry iota rules whose
        // install-computed fields the annotation fills in; `Empty` and
        // `False` have no rules at all and compare equal.
        assert_eq!(differed, 4);
    }

    /// A raw block matches itself up to the canonical form, which is the
    /// property the pin match relies on.
    #[test]
    fn raw_pins_match_themselves() {
        for k in [
            BasisKind::EqK,
            BasisKind::NatK,
            BasisKind::PunitK,
            BasisKind::EmptyK,
            BasisKind::FalseK,
            BasisKind::QuotK,
        ] {
            assert!(crate::frontend::export::canon_eq_list(
                &basis_decls(&k),
                &basis_decls(&k)
            ));
        }
    }
}
