-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [level_name]: external functions.
-- This is a template file: rename it to "FunsExternal.lean" and fill the holes.
import Aeneas
import LevelName.Types
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048
open level_name

/-- [alloc::rc::{alloc::rc::Rc<T>}::new]:
    Source: '/rustc/library/alloc/src/rc.rs', lines 423:4-423:33
    Name pattern: [alloc::rc::{alloc::rc::Rc<@T>}::new]
    Visibility: public -/
@[rust_fun "alloc::rc::{alloc::rc::Rc<@T>}::new"]
axiom alloc.rc.Rc.new {T : Type} : T → Result (alloc.rc.Rc T)

/-- [alloc::rc::{alloc::rc::Rc<T>}::ptr_eq]:
    Source: '/rustc/library/alloc/src/rc.rs', lines 2025:4-2025:52
    Name pattern: [alloc::rc::{alloc::rc::Rc<@T>}::ptr_eq]
    Visibility: public -/
@[rust_fun "alloc::rc::{alloc::rc::Rc<@T>}::ptr_eq"]
axiom alloc.rc.Rc.ptr_eq
  {T : Type} (A : Type) : alloc.rc.Rc T → alloc.rc.Rc T → Result Bool

/-- [alloc::rc::{impl core::ops::deref::Deref<T> for alloc::rc::Rc<T>}::deref]:
    Source: '/rustc/library/alloc/src/rc.rs', lines 2440:4-2440:25
    Name pattern: [alloc::rc::{core::ops::deref::Deref<alloc::rc::Rc<@T>, @T>}::deref]
    Visibility: public -/
@[rust_fun
  "alloc::rc::{core::ops::deref::Deref<alloc::rc::Rc<@T>, @T>}::deref"]
axiom alloc.rc.Rc.Insts.CoreOpsDerefDeref.deref
  {T : Type} (A : Type) : alloc.rc.Rc T → Result T

/-- [alloc::rc::{impl core::clone::Clone for alloc::rc::Rc<T>}::clone]:
    Source: '/rustc/library/alloc/src/rc.rs', lines 2524:4-2524:27
    Name pattern: [alloc::rc::{core::clone::Clone<alloc::rc::Rc<@T>>}::clone]
    Visibility: public -/
@[rust_fun "alloc::rc::{core::clone::Clone<alloc::rc::Rc<@T>>}::clone"]
axiom alloc.rc.Rc.Insts.CoreCloneClone.clone
  {T : Type} {A : Type} (coreallocAllocatorCloneInst :
  core.alloc.AllocatorClone A) :
  alloc.rc.Rc T → Result (alloc.rc.Rc T)

