-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [level_name]: function definitions
import Aeneas
import LevelName.Types
import LevelName.FunsExternal
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace level_name

/-- Trait implementation: [alloc::alloc::{impl core::alloc::AllocatorClone for alloc::alloc::Global}]
    Source: '/rustc/library/alloc/src/alloc.rs', lines 62:0-62:50
    Name pattern: [core::alloc::AllocatorClone<alloc::alloc::Global>] -/
@[reducible, rust_trait_impl
  "core::alloc::AllocatorClone<alloc::alloc::Global>"]
def alloc.alloc.Global.Insts.CoreAllocAllocatorClone :
  core.alloc.AllocatorClone Global := {
  cloneCloneInst := core.core.clone.CloneGlobal
}

/-- [level_name::level::hash_data]:
    Source: 'src/level.rs', lines 37:0-39:1
    Visibility: public -/
def level.hash_data (u : level.Level) : Result Std.U64 := do
  let ln ← alloc.rc.Rc.Insts.CoreOpsDerefDeref.deref Global u._0
  ok ln.hash

/-- [level_name::level::zero]:
    Source: 'src/level.rs', lines 42:0-44:1
    Visibility: public -/
def level.zero : Result level.Level := do
  let r ← alloc.rc.Rc.new (level.LevelNode.mk 1#u64 level.LevelKind.Zero)
  ok (level.Level.mk r)

/-- [level_name::name::mix_hash]:
    Source: 'src/name.rs', lines 34:0-41:1
    Visibility: public -/
def name.mix_hash (h : Std.U64) (k : Std.U64) : Result Std.U64 := do
  let k1 ← lift (core.num.U64.wrapping_mul k 14313749767032793493#u64)
  let i ← k1 >>> 47#i32
  let k2 ← lift (k1 ^^^ i)
  let k3 ← lift (k2 ^^^ 14313749767032793493#u64)
  let h1 ← lift (h ^^^ k3)
  ok (core.num.U64.wrapping_mul h1 14313749767032793493#u64)

/-- [level_name::level::succ]:
    Source: 'src/level.rs', lines 47:0-50:1
    Visibility: public -/
def level.succ (u : level.Level) : Result level.Level := do
  let i ← level.hash_data u
  let h ← name.mix_hash 3#u64 i
  let r ← alloc.rc.Rc.new (level.LevelNode.mk h (level.LevelKind.Succ u))
  ok (level.Level.mk r)

/-- [level_name::level::max]:
    Source: 'src/level.rs', lines 54:0-57:1
    Visibility: public -/
def level.max (u : level.Level) (v : level.Level) : Result level.Level := do
  let i ← level.hash_data u
  let i1 ← level.hash_data v
  let i2 ← name.mix_hash i i1
  let h ← name.mix_hash 5#u64 i2
  let r ← alloc.rc.Rc.new (level.LevelNode.mk h (level.LevelKind.Max u v))
  ok (level.Level.mk r)

/-- [level_name::level::imax]:
    Source: 'src/level.rs', lines 61:0-64:1
    Visibility: public -/
def level.imax (u : level.Level) (v : level.Level) : Result level.Level := do
  let i ← level.hash_data u
  let i1 ← level.hash_data v
  let i2 ← name.mix_hash i i1
  let h ← name.mix_hash 7#u64 i2
  let r ← alloc.rc.Rc.new (level.LevelNode.mk h (level.LevelKind.Imax u v))
  ok (level.Level.mk r)

/-- [level_name::name::hash_data]:
    Source: 'src/name.rs', lines 69:0-71:1
    Visibility: public -/
def name.hash_data (n : name.Name) : Result Std.U64 := do
  let nn ← alloc.rc.Rc.Insts.CoreOpsDerefDeref.deref Global n._0
  ok nn.hash

/-- [level_name::level::param]:
    Source: 'src/level.rs', lines 67:0-70:1
    Visibility: public -/
def level.param (n : name.Name) : Result level.Level := do
  let i ← name.hash_data n
  let h ← name.mix_hash 11#u64 i
  let r ← alloc.rc.Rc.new (level.LevelNode.mk h (level.LevelKind.Param n))
  ok (level.Level.mk r)

/-- [level_name::level::dup]:
    Source: 'src/level.rs', lines 73:0-75:1
    Visibility: public -/
def level.dup (u : level.Level) : Result level.Level := do
  let r ←
    alloc.rc.Rc.Insts.CoreCloneClone.clone
      alloc.alloc.Global.Insts.CoreAllocAllocatorClone u._0
  ok (level.Level.mk r)

/-- [level_name::level::ptr_eq]:
    Source: 'src/level.rs', lines 78:0-80:1
    Visibility: public -/
def level.ptr_eq (a : level.Level) (b : level.Level) : Result Bool := do
  alloc.rc.Rc.ptr_eq Global a._0 b._0

/-- [level_name::name::str_eq_from]:
    Source: 'src/name.rs', lines 113:0-121:1
    Visibility: public -/
def name.str_eq_from
  (a : alloc.vec.Vec Std.U32) (b : alloc.vec.Vec Std.U32) (i : Std.Usize) :
  Result Bool
  := do
  let i1 := alloc.vec.Vec.len a
  if i >= i1
  then ok true
  else
    let i2 ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice Std.U32) a i
    let i3 ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice Std.U32) b i
    if i2 != i3
    then ok false
    else let i4 ← i + 1#usize
         name.str_eq_from a b i4
partial_fixpoint

/-- [level_name::name::str_eq]:
    Source: 'src/name.rs', lines 104:0-110:1
    Visibility: public -/
def name.str_eq
  (a : alloc.vec.Vec Std.U32) (b : alloc.vec.Vec Std.U32) : Result Bool := do
  let i := alloc.vec.Vec.len a
  let i1 := alloc.vec.Vec.len b
  if i != i1
  then ok false
  else name.str_eq_from a b 0#usize

/-- [level_name::name::ptr_eq]:
    Source: 'src/name.rs', lines 99:0-101:1
    Visibility: public -/
def name.ptr_eq (a : name.Name) (b : name.Name) : Result Bool := do
  alloc.rc.Rc.ptr_eq Global a._0 b._0

/-- [level_name::name::beq]:
    Source: 'src/name.rs', lines 128:0-141:1
    Visibility: public -/
def name.beq (a : name.Name) (b : name.Name) : Result Bool := do
  let b1 ← name.ptr_eq a b
  if b1
  then ok true
  else
    let i ← name.hash_data a
    let i1 ← name.hash_data b
    if i != i1
    then ok false
    else
      let nn ← alloc.rc.Rc.Insts.CoreOpsDerefDeref.deref Global a._0
      let nn1 ← alloc.rc.Rc.Insts.CoreOpsDerefDeref.deref Global b._0
      match nn.kind with
      | name.NameKind.Anonymous =>
        match nn1.kind with
        | name.NameKind.Anonymous => ok true
        | name.NameKind.Str _ _ => ok false
        | name.NameKind.Num _ _ => ok false
      | name.NameKind.Str p s =>
        match nn1.kind with
        | name.NameKind.Anonymous => ok false
        | name.NameKind.Str q t =>
          let b2 ← name.beq p q
          if b2
          then name.str_eq s t
          else ok false
        | name.NameKind.Num _ _ => ok false
      | name.NameKind.Num p m =>
        match nn1.kind with
        | name.NameKind.Anonymous => ok false
        | name.NameKind.Str _ _ => ok false
        | name.NameKind.Num q n =>
          let b2 ← name.beq p q
          if b2
          then lift (core.cmp.impls.PartialEqU64.eq m n)
          else ok false
partial_fixpoint

/-- [level_name::level::beq]:
    Source: 'src/level.rs', lines 85:0-100:1
    Visibility: public -/
def level.beq (a : level.Level) (b : level.Level) : Result Bool := do
  let b1 ← level.ptr_eq a b
  if b1
  then ok true
  else
    let i ← level.hash_data a
    let i1 ← level.hash_data b
    if i != i1
    then ok false
    else
      let ln ← alloc.rc.Rc.Insts.CoreOpsDerefDeref.deref Global a._0
      let ln1 ← alloc.rc.Rc.Insts.CoreOpsDerefDeref.deref Global b._0
      match ln.kind with
      | level.LevelKind.Zero =>
        match ln1.kind with
        | level.LevelKind.Zero => ok true
        | level.LevelKind.Succ _ => ok false
        | level.LevelKind.Max _ _ => ok false
        | level.LevelKind.Imax _ _ => ok false
        | level.LevelKind.Param _ => ok false
      | level.LevelKind.Succ u =>
        match ln1.kind with
        | level.LevelKind.Zero => ok false
        | level.LevelKind.Succ v => level.beq u v
        | level.LevelKind.Max _ _ => ok false
        | level.LevelKind.Imax _ _ => ok false
        | level.LevelKind.Param _ => ok false
      | level.LevelKind.Max u1 v1 =>
        match ln1.kind with
        | level.LevelKind.Zero => ok false
        | level.LevelKind.Succ _ => ok false
        | level.LevelKind.Max u2 v2 =>
          let b2 ← level.beq u1 u2
          if b2
          then level.beq v1 v2
          else ok false
        | level.LevelKind.Imax _ _ => ok false
        | level.LevelKind.Param _ => ok false
      | level.LevelKind.Imax u1 v1 =>
        match ln1.kind with
        | level.LevelKind.Zero => ok false
        | level.LevelKind.Succ _ => ok false
        | level.LevelKind.Max _ _ => ok false
        | level.LevelKind.Imax u2 v2 =>
          let b2 ← level.beq u1 u2
          if b2
          then level.beq v1 v2
          else ok false
        | level.LevelKind.Param _ => ok false
      | level.LevelKind.Param n =>
        match ln1.kind with
        | level.LevelKind.Zero => ok false
        | level.LevelKind.Succ _ => ok false
        | level.LevelKind.Max _ _ => ok false
        | level.LevelKind.Imax _ _ => ok false
        | level.LevelKind.Param m => name.beq n m
partial_fixpoint

/-- [level_name::level::is_zero_kind]:
    Source: 'src/level.rs', lines 105:0-110:1
    Visibility: public -/
def level.is_zero_kind (u : level.Level) : Result Bool := do
  let ln ← alloc.rc.Rc.Insts.CoreOpsDerefDeref.deref Global u._0
  match ln.kind with
  | level.LevelKind.Zero => ok true
  | level.LevelKind.Succ _ => ok false
  | level.LevelKind.Max _ _ => ok false
  | level.LevelKind.Imax _ _ => ok false
  | level.LevelKind.Param _ => ok false

/-- [level_name::level::is_one_kind]:
    Source: 'src/level.rs', lines 113:0-118:1
    Visibility: public -/
def level.is_one_kind (u : level.Level) : Result Bool := do
  let ln ← alloc.rc.Rc.Insts.CoreOpsDerefDeref.deref Global u._0
  match ln.kind with
  | level.LevelKind.Zero => ok false
  | level.LevelKind.Succ v => level.is_zero_kind v
  | level.LevelKind.Max _ _ => ok false
  | level.LevelKind.Imax _ _ => ok false
  | level.LevelKind.Param _ => ok false

/-- [level_name::level::level_has_param]:
    Source: 'src/level.rs', lines 121:0-129:1
    Visibility: public -/
def level.level_has_param (u : level.Level) : Result Bool := do
  let ln ← alloc.rc.Rc.Insts.CoreOpsDerefDeref.deref Global u._0
  match ln.kind with
  | level.LevelKind.Zero => ok false
  | level.LevelKind.Succ v => level.level_has_param v
  | level.LevelKind.Max a b =>
    let b1 ← level.level_has_param a
    if b1
    then ok true
    else level.level_has_param b
  | level.LevelKind.Imax a b =>
    let b1 ← level.level_has_param a
    if b1
    then ok true
    else level.level_has_param b
  | level.LevelKind.Param _ => ok true
partial_fixpoint

/-- [level_name::level::levels_have_param_from]:
    Source: 'src/level.rs', lines 137:0-143:1
    Visibility: public -/
def level.levels_have_param_from
  (us : alloc.vec.Vec level.Level) (i : Std.Usize) : Result Bool := do
  let i1 := alloc.vec.Vec.len us
  if i >= i1
  then ok false
  else
    let l ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice level.Level)
        us i
    let b ← level.level_has_param l
    if b
    then ok true
    else let i2 ← i + 1#usize
         level.levels_have_param_from us i2
partial_fixpoint

/-- [level_name::level::levels_have_param]:
    Source: 'src/level.rs', lines 132:0-134:1
    Visibility: public -/
def level.levels_have_param
  (us : alloc.vec.Vec level.Level) : Result Bool := do
  level.levels_have_param_from us 0#usize

/-- [level_name::level::level_hash]:
    Source: 'src/level.rs', lines 146:0-148:1
    Visibility: public -/
def level.level_hash (u : level.Level) : Result Std.U64 := do
  level.hash_data u

/-- [level_name::level::levels_hash_from]:
    Source: 'src/level.rs', lines 156:0-162:1
    Visibility: public -/
def level.levels_hash_from
  (us : alloc.vec.Vec level.Level) (i : Std.Usize) : Result Std.U64 := do
  let i1 := alloc.vec.Vec.len us
  if i >= i1
  then ok 13#u64
  else
    let l ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice level.Level)
        us i
    let i2 ← level.level_hash l
    let i3 ← i + 1#usize
    let i4 ← level.levels_hash_from us i3
    name.mix_hash i2 i4
partial_fixpoint

/-- [level_name::level::levels_hash]:
    Source: 'src/level.rs', lines 151:0-153:1
    Visibility: public -/
def level.levels_hash (us : alloc.vec.Vec level.Level) : Result Std.U64 := do
  level.levels_hash_from us 0#usize

/-- [level_name::name::dup]:
    Source: 'src/name.rs', lines 93:0-95:1
    Visibility: public -/
def name.dup (n : name.Name) : Result name.Name := do
  let r ←
    alloc.rc.Rc.Insts.CoreCloneClone.clone
      alloc.alloc.Global.Insts.CoreAllocAllocatorClone n._0
  ok (name.Name.mk r)

/-- [level_name::level::subst_go]:
    Source: 'src/level.rs', lines 177:0-185:1
    Visibility: public -/
def level.subst_go
  (ks : alloc.vec.Vec name.Name) (vs : alloc.vec.Vec level.Level)
  (i : Std.Usize) (n : name.Name) :
  Result level.Level
  := do
  let i1 := alloc.vec.Vec.len ks
  if i >= i1
  then let n1 ← name.dup n
       level.param n1
  else
    let i2 := alloc.vec.Vec.len vs
    if i >= i2
    then let n1 ← name.dup n
         level.param n1
    else
      let n1 ←
        alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice name.Name)
          ks i
      let b ← name.beq n1 n
      if b
      then
        let l ←
          alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice
            level.Level) vs i
        level.dup l
      else let i3 ← i + 1#usize
           level.subst_go ks vs i3 n
partial_fixpoint

/-- [level_name::level::subst]:
    Source: 'src/level.rs', lines 165:0-173:1
    Visibility: public -/
def level.subst
  (ks : alloc.vec.Vec name.Name) (vs : alloc.vec.Vec level.Level)
  (u : level.Level) :
  Result level.Level
  := do
  let ln ← alloc.rc.Rc.Insts.CoreOpsDerefDeref.deref Global u._0
  match ln.kind with
  | level.LevelKind.Zero => level.zero
  | level.LevelKind.Succ l => let l1 ← level.subst ks vs l
                              level.succ l1
  | level.LevelKind.Max l r =>
    let l1 ← level.subst ks vs l
    let l2 ← level.subst ks vs r
    level.max l1 l2
  | level.LevelKind.Imax l r =>
    let l1 ← level.subst ks vs l
    let l2 ← level.subst ks vs r
    level.imax l1 l2
  | level.LevelKind.Param n => level.subst_go ks vs 0#usize n
partial_fixpoint

/-- [level_name::name::contains_from]:
    Source: 'src/name.rs', lines 144:0-152:1
    Visibility: public -/
def name.contains_from
  (ns : alloc.vec.Vec name.Name) (i : Std.Usize) (n : name.Name) :
  Result Bool
  := do
  let i1 := alloc.vec.Vec.len ns
  if i >= i1
  then ok false
  else
    let n1 ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice name.Name) ns
        i
    let b ← name.beq n1 n
    if b
    then ok true
    else let i2 ← i + 1#usize
         name.contains_from ns i2 n
partial_fixpoint

/-- [level_name::name::contains]:
    Source: 'src/name.rs', lines 155:0-157:1
    Visibility: public -/
def name.contains
  (ns : alloc.vec.Vec name.Name) (n : name.Name) : Result Bool := do
  name.contains_from ns 0#usize n

/-- [level_name::level::all_params_defined]:
    Source: 'src/level.rs', lines 188:0-196:1
    Visibility: public -/
def level.all_params_defined
  (params : alloc.vec.Vec name.Name) (u : level.Level) : Result Bool := do
  let ln ← alloc.rc.Rc.Insts.CoreOpsDerefDeref.deref Global u._0
  match ln.kind with
  | level.LevelKind.Zero => ok true
  | level.LevelKind.Succ l => level.all_params_defined params l
  | level.LevelKind.Max l r =>
    let b ← level.all_params_defined params l
    if b
    then level.all_params_defined params r
    else ok false
  | level.LevelKind.Imax l r =>
    let b ← level.all_params_defined params l
    if b
    then level.all_params_defined params r
    else ok false
  | level.LevelKind.Param n => name.contains params n
partial_fixpoint

/-- [level_name::level::is_never_zero]:
    Source: 'src/level.rs', lines 199:0-207:1
    Visibility: public -/
def level.is_never_zero (u : level.Level) : Result Bool := do
  let ln ← alloc.rc.Rc.Insts.CoreOpsDerefDeref.deref Global u._0
  match ln.kind with
  | level.LevelKind.Zero => ok false
  | level.LevelKind.Succ _ => ok true
  | level.LevelKind.Max l r =>
    let b ← level.is_never_zero l
    if b
    then ok true
    else level.is_never_zero r
  | level.LevelKind.Imax _ r => level.is_never_zero r
  | level.LevelKind.Param _ => ok false
partial_fixpoint

/-- [level_name::level::combining]:
    Source: 'src/level.rs', lines 210:0-217:1
    Visibility: public -/
def level.combining
  (l : level.Level) (r : level.Level) : Result level.Level := do
  let ln ← alloc.rc.Rc.Insts.CoreOpsDerefDeref.deref Global l._0
  let ln1 ← alloc.rc.Rc.Insts.CoreOpsDerefDeref.deref Global r._0
  match ln.kind with
  | level.LevelKind.Zero => level.dup r
  | level.LevelKind.Succ a =>
    match ln1.kind with
    | level.LevelKind.Zero => level.dup l
    | level.LevelKind.Succ b => let l1 ← level.combining a b
                                level.succ l1
    | level.LevelKind.Max _ _ =>
      let l1 ← level.dup l
      let l2 ← level.dup r
      level.max l1 l2
    | level.LevelKind.Imax _ _ =>
      let l1 ← level.dup l
      let l2 ← level.dup r
      level.max l1 l2
    | level.LevelKind.Param _ =>
      let l1 ← level.dup l
      let l2 ← level.dup r
      level.max l1 l2
  | level.LevelKind.Max _ _ =>
    match ln1.kind with
    | level.LevelKind.Zero => level.dup l
    | level.LevelKind.Succ _ =>
      let l1 ← level.dup l
      let l2 ← level.dup r
      level.max l1 l2
    | level.LevelKind.Max _ _ =>
      let l1 ← level.dup l
      let l2 ← level.dup r
      level.max l1 l2
    | level.LevelKind.Imax _ _ =>
      let l1 ← level.dup l
      let l2 ← level.dup r
      level.max l1 l2
    | level.LevelKind.Param _ =>
      let l1 ← level.dup l
      let l2 ← level.dup r
      level.max l1 l2
  | level.LevelKind.Imax _ _ =>
    match ln1.kind with
    | level.LevelKind.Zero => level.dup l
    | level.LevelKind.Succ _ =>
      let l1 ← level.dup l
      let l2 ← level.dup r
      level.max l1 l2
    | level.LevelKind.Max _ _ =>
      let l1 ← level.dup l
      let l2 ← level.dup r
      level.max l1 l2
    | level.LevelKind.Imax _ _ =>
      let l1 ← level.dup l
      let l2 ← level.dup r
      level.max l1 l2
    | level.LevelKind.Param _ =>
      let l1 ← level.dup l
      let l2 ← level.dup r
      level.max l1 l2
  | level.LevelKind.Param _ =>
    match ln1.kind with
    | level.LevelKind.Zero => level.dup l
    | level.LevelKind.Succ _ =>
      let l1 ← level.dup l
      let l2 ← level.dup r
      level.max l1 l2
    | level.LevelKind.Max _ _ =>
      let l1 ← level.dup l
      let l2 ← level.dup r
      level.max l1 l2
    | level.LevelKind.Imax _ _ =>
      let l1 ← level.dup l
      let l2 ← level.dup r
      level.max l1 l2
    | level.LevelKind.Param _ =>
      let l1 ← level.dup l
      let l2 ← level.dup r
      level.max l1 l2
partial_fixpoint

/-- [level_name::level::simplify]:
    Source: 'src/level.rs', lines 220:0-240:1
    Visibility: public -/
def level.simplify (u : level.Level) : Result level.Level := do
  let ln ← alloc.rc.Rc.Insts.CoreOpsDerefDeref.deref Global u._0
  match ln.kind with
  | level.LevelKind.Zero => level.zero
  | level.LevelKind.Succ l => let l1 ← level.simplify l
                              level.succ l1
  | level.LevelKind.Max l r =>
    let l1 ← level.simplify l
    let l2 ← level.simplify r
    level.combining l1 l2
  | level.LevelKind.Imax l r =>
    let ls ← level.simplify l
    let rs ← level.simplify r
    let b ← level.is_zero_kind ls
    if b
    then ok rs
    else
      let b1 ← level.is_one_kind ls
      if b1
      then ok rs
      else
        let ln1 ← alloc.rc.Rc.Insts.CoreOpsDerefDeref.deref Global rs._0
        match ln1.kind with
        | level.LevelKind.Zero => level.zero
        | level.LevelKind.Succ _ => level.combining ls rs
        | level.LevelKind.Max _ _ =>
          let l1 ← level.dup ls
          let l2 ← level.dup rs
          level.imax l1 l2
        | level.LevelKind.Imax _ _ =>
          let l1 ← level.dup ls
          let l2 ← level.dup rs
          level.imax l1 l2
        | level.LevelKind.Param _ =>
          let l1 ← level.dup ls
          let l2 ← level.dup rs
          level.imax l1 l2
  | level.LevelKind.Param n => let n1 ← name.dup n
                               level.param n1
partial_fixpoint

/-- [level_name::name::singleton]:
    Source: 'src/name.rs', lines 160:0-164:1
    Visibility: public -/
def name.singleton (n : name.Name) : Result (alloc.vec.Vec name.Name) := do
  let n1 ← name.dup n
  alloc.vec.Vec.push (alloc.vec.Vec.new name.Name) n1

/-- [level_name::level::singleton]:
    Source: 'src/level.rs', lines 394:0-398:1
    Visibility: public -/
def level.singleton
  (u : level.Level) : Result (alloc.vec.Vec level.Level) := do
  alloc.vec.Vec.push (alloc.vec.Vec.new level.Level) u

/-- [level_name::level::is_imax_param]:
    Source: 'src/level.rs', lines 294:0-302:1
    Visibility: public -/
def level.is_imax_param (u : level.Level) : Result Bool := do
  let ln ← alloc.rc.Rc.Insts.CoreOpsDerefDeref.deref Global u._0
  match ln.kind with
  | level.LevelKind.Zero => ok false
  | level.LevelKind.Succ _ => ok false
  | level.LevelKind.Max _ _ => ok false
  | level.LevelKind.Imax _ b =>
    let ln1 ← alloc.rc.Rc.Insts.CoreOpsDerefDeref.deref Global b._0
    match ln1.kind with
    | level.LevelKind.Zero => ok false
    | level.LevelKind.Succ _ => ok false
    | level.LevelKind.Max _ _ => ok false
    | level.LevelKind.Imax _ _ => ok false
    | level.LevelKind.Param _ => ok true
  | level.LevelKind.Param _ => ok false

mutual

/-- [level_name::level::leq_core]:
    Source: 'src/level.rs', lines 244:0-254:1
    Visibility: public -/
def level.leq_core
  (fuel : Std.U64) (l : level.Level) (r : level.Level) (diff : Std.I64) :
  Result (Option Bool)
  := do
  if fuel = 0#u64
  then ok none
  else
    let b ← level.is_zero_kind l
    if b
    then
      if diff >= 0#i64
      then ok (some true)
      else
        let b1 ← level.is_zero_kind r
        if b1
        then
          if diff < 0#i64
          then ok (some false)
          else let i ← fuel - 1#u64
               level.rest i l r diff
        else let i ← fuel - 1#u64
             level.rest i l r diff
    else
      let b1 ← level.is_zero_kind r
      if b1
      then
        if diff < 0#i64
        then ok (some false)
        else let i ← fuel - 1#u64
             level.rest i l r diff
      else let i ← fuel - 1#u64
           level.rest i l r diff
partial_fixpoint

/-- [level_name::level::rest]:
    Source: 'src/level.rs', lines 258:0-289:1
    Visibility: public -/
def level.rest
  (fuel : Std.U64) (l : level.Level) (r : level.Level) (diff : Std.I64) :
  Result (Option Bool)
  := do
  let ln ← alloc.rc.Rc.Insts.CoreOpsDerefDeref.deref Global l._0
  let ln1 ← alloc.rc.Rc.Insts.CoreOpsDerefDeref.deref Global r._0
  match ln.kind with
  | level.LevelKind.Zero =>
    match ln1.kind with
    | level.LevelKind.Zero => level.imax_rules fuel l r diff
    | level.LevelKind.Succ s =>
      let i ← diff + 1#i64
      level.leq_core fuel l s i
    | level.LevelKind.Max x y =>
      let o ← level.leq_core fuel l x diff
      match o with
      | none => ok none
      | some b => if b
                  then ok o
                  else level.leq_core fuel l y diff
    | level.LevelKind.Imax _ _ => level.imax_rules fuel l r diff
    | level.LevelKind.Param _ => ok (some (diff >= 0#i64))
  | level.LevelKind.Succ s => let i ← diff - 1#i64
                              level.leq_core fuel s r i
  | level.LevelKind.Max a b =>
    match ln1.kind with
    | level.LevelKind.Zero =>
      let o ← level.leq_core fuel a r diff
      match o with
      | none => ok none
      | some b1 => if b1
                   then level.leq_core fuel b r diff
                   else ok o
    | level.LevelKind.Succ s =>
      let i ← diff + 1#i64
      level.leq_core fuel l s i
    | level.LevelKind.Max _ _ =>
      let o ← level.leq_core fuel a r diff
      match o with
      | none => ok none
      | some b1 => if b1
                   then level.leq_core fuel b r diff
                   else ok o
    | level.LevelKind.Imax _ _ =>
      let o ← level.leq_core fuel a r diff
      match o with
      | none => ok none
      | some b1 => if b1
                   then level.leq_core fuel b r diff
                   else ok o
    | level.LevelKind.Param _ =>
      let o ← level.leq_core fuel a r diff
      match o with
      | none => ok none
      | some b1 => if b1
                   then level.leq_core fuel b r diff
                   else ok o
  | level.LevelKind.Imax a b =>
    match ln1.kind with
    | level.LevelKind.Zero => level.imax_rules fuel l r diff
    | level.LevelKind.Succ s =>
      let i ← diff + 1#i64
      level.leq_core fuel l s i
    | level.LevelKind.Max _ _ => level.imax_rules fuel l r diff
    | level.LevelKind.Imax x y =>
      let b1 ← level.beq a x
      if b1
      then
        let b2 ← level.beq b y
        if b2
        then
          if diff >= 0#i64
          then ok (some true)
          else level.imax_rules fuel l r diff
        else level.imax_rules fuel l r diff
      else level.imax_rules fuel l r diff
    | level.LevelKind.Param _ => level.imax_rules fuel l r diff
  | level.LevelKind.Param a =>
    match ln1.kind with
    | level.LevelKind.Zero => ok (some false)
    | level.LevelKind.Succ s =>
      let i ← diff + 1#i64
      level.leq_core fuel l s i
    | level.LevelKind.Max x y =>
      let o ← level.leq_core fuel l x diff
      match o with
      | none => ok none
      | some b => if b
                  then ok o
                  else level.leq_core fuel l y diff
    | level.LevelKind.Imax _ _ => level.imax_rules fuel l r diff
    | level.LevelKind.Param x =>
      let b ← name.beq a x
      if b
      then ok (some (diff >= 0#i64))
      else ok (some false)
partial_fixpoint

/-- [level_name::level::imax_rules]:
    Source: 'src/level.rs', lines 307:0-315:1
    Visibility: public -/
def level.imax_rules
  (fuel : Std.U64) (l : level.Level) (r : level.Level) (diff : Std.I64) :
  Result (Option Bool)
  := do
  let b ← level.is_imax_param l
  if b
  then level.by_cases_left fuel l r diff
  else
    let b1 ← level.is_imax_param r
    if b1
    then level.by_cases_right fuel l r diff
    else level.imax_rules_distrib fuel l r diff
partial_fixpoint

/-- [level_name::level::by_cases_left]:
    Source: 'src/level.rs', lines 318:0-326:1
    Visibility: public -/
def level.by_cases_left
  (fuel : Std.U64) (l : level.Level) (r : level.Level) (diff : Std.I64) :
  Result (Option Bool)
  := do
  let ln ← alloc.rc.Rc.Insts.CoreOpsDerefDeref.deref Global l._0
  match ln.kind with
  | level.LevelKind.Zero => ok none
  | level.LevelKind.Succ _ => ok none
  | level.LevelKind.Max _ _ => ok none
  | level.LevelKind.Imax _ b =>
    let ln1 ← alloc.rc.Rc.Insts.CoreOpsDerefDeref.deref Global b._0
    match ln1.kind with
    | level.LevelKind.Zero => ok none
    | level.LevelKind.Succ _ => ok none
    | level.LevelKind.Max _ _ => ok none
    | level.LevelKind.Imax _ _ => ok none
    | level.LevelKind.Param p => level.by_cases fuel p l r diff
  | level.LevelKind.Param _ => ok none
partial_fixpoint

/-- [level_name::level::by_cases_right]:
    Source: 'src/level.rs', lines 329:0-337:1
    Visibility: public -/
def level.by_cases_right
  (fuel : Std.U64) (l : level.Level) (r : level.Level) (diff : Std.I64) :
  Result (Option Bool)
  := do
  let ln ← alloc.rc.Rc.Insts.CoreOpsDerefDeref.deref Global r._0
  match ln.kind with
  | level.LevelKind.Zero => ok none
  | level.LevelKind.Succ _ => ok none
  | level.LevelKind.Max _ _ => ok none
  | level.LevelKind.Imax _ b =>
    let ln1 ← alloc.rc.Rc.Insts.CoreOpsDerefDeref.deref Global b._0
    match ln1.kind with
    | level.LevelKind.Zero => ok none
    | level.LevelKind.Succ _ => ok none
    | level.LevelKind.Max _ _ => ok none
    | level.LevelKind.Imax _ _ => ok none
    | level.LevelKind.Param p => level.by_cases fuel p l r diff
  | level.LevelKind.Param _ => ok none
partial_fixpoint

/-- [level_name::level::imax_rules_distrib]:
    Source: 'src/level.rs', lines 340:0-355:1
    Visibility: public -/
def level.imax_rules_distrib
  (fuel : Std.U64) (l : level.Level) (r : level.Level) (diff : Std.I64) :
  Result (Option Bool)
  := do
  let ln ← alloc.rc.Rc.Insts.CoreOpsDerefDeref.deref Global l._0
  match ln.kind with
  | level.LevelKind.Zero => level.imax_rules_distrib_right fuel l r diff
  | level.LevelKind.Succ _ => level.imax_rules_distrib_right fuel l r diff
  | level.LevelKind.Max _ _ => level.imax_rules_distrib_right fuel l r diff
  | level.LevelKind.Imax a b =>
    let ln1 ← alloc.rc.Rc.Insts.CoreOpsDerefDeref.deref Global b._0
    match ln1.kind with
    | level.LevelKind.Zero => level.imax_rules_distrib_right fuel l r diff
    | level.LevelKind.Succ _ => level.imax_rules_distrib_right fuel l r diff
    | level.LevelKind.Max x y =>
      let l1 ← level.dup a
      let l2 ← level.dup x
      let l3 ← level.imax l1 l2
      let l4 ← level.dup y
      let l5 ← level.imax l1 l4
      let l6 ← level.max l3 l5
      let nl ← level.simplify l6
      level.leq_core fuel nl r diff
    | level.LevelKind.Imax x y =>
      let l1 ← level.dup a
      let l2 ← level.dup y
      let l3 ← level.imax l1 l2
      let l4 ← level.dup x
      let l5 ← level.imax l4 l2
      let nl ← level.max l3 l5
      level.leq_core fuel nl r diff
    | level.LevelKind.Param _ => level.imax_rules_distrib_right fuel l r diff
  | level.LevelKind.Param _ => level.imax_rules_distrib_right fuel l r diff
partial_fixpoint

/-- [level_name::level::imax_rules_distrib_right]:
    Source: 'src/level.rs', lines 358:0-373:1
    Visibility: public -/
def level.imax_rules_distrib_right
  (fuel : Std.U64) (l : level.Level) (r : level.Level) (diff : Std.I64) :
  Result (Option Bool)
  := do
  let ln ← alloc.rc.Rc.Insts.CoreOpsDerefDeref.deref Global r._0
  match ln.kind with
  | level.LevelKind.Zero => ok none
  | level.LevelKind.Succ _ => ok none
  | level.LevelKind.Max _ _ => ok none
  | level.LevelKind.Imax x y =>
    let ln1 ← alloc.rc.Rc.Insts.CoreOpsDerefDeref.deref Global y._0
    match ln1.kind with
    | level.LevelKind.Zero => ok none
    | level.LevelKind.Succ _ => ok none
    | level.LevelKind.Max j k =>
      let l1 ← level.dup x
      let l2 ← level.dup j
      let l3 ← level.imax l1 l2
      let l4 ← level.dup k
      let l5 ← level.imax l1 l4
      let l6 ← level.max l3 l5
      let nr ← level.simplify l6
      level.leq_core fuel l nr diff
    | level.LevelKind.Imax j k =>
      let l1 ← level.dup x
      let l2 ← level.dup k
      let l3 ← level.imax l1 l2
      let l4 ← level.dup j
      let l5 ← level.imax l4 l2
      let nr ← level.max l3 l5
      level.leq_core fuel l nr diff
    | level.LevelKind.Param _ => ok none
  | level.LevelKind.Param _ => ok none
partial_fixpoint

/-- [level_name::level::by_cases]:
    Source: 'src/level.rs', lines 376:0-391:1
    Visibility: public -/
def level.by_cases
  (fuel : Std.U64) (p : name.Name) (l : level.Level) (r : level.Level)
  (diff : Std.I64) :
  Result (Option Bool)
  := do
  let ks ← name.singleton p
  let l1 ← level.zero
  let vz ← level.singleton l1
  let l2 ← level.subst ks vz l
  let l0 ← level.simplify l2
  let l3 ← level.subst ks vz r
  let r0 ← level.simplify l3
  let o ← level.leq_core fuel l0 r0 diff
  match o with
  | none => ok none
  | some b =>
    if b
    then
      let n ← name.dup p
      let l4 ← level.param n
      let l5 ← level.succ l4
      let vp ← level.singleton l5
      let l6 ← level.subst ks vp l
      let ls ← level.simplify l6
      let l7 ← level.subst ks vp r
      let rs ← level.simplify l7
      level.leq_core fuel ls rs diff
    else ok o
partial_fixpoint

end

/-- [level_name::level::default_fuel]:
    Source: 'src/level.rs', lines 401:0-403:1
    Visibility: public -/
def level.default_fuel : Result Std.U64 := do
  ok 10000#u64

/-- [level_name::level::leq]:
    Source: 'src/level.rs', lines 406:0-408:1
    Visibility: public -/
def level.leq (l : level.Level) (r : level.Level) : Result (Option Bool) := do
  let i ← level.default_fuel
  let l1 ← level.simplify l
  let l2 ← level.simplify r
  level.leq_core i l1 l2 0#i64

/-- [level_name::level::is_equiv]:
    Source: 'src/level.rs', lines 411:0-423:1
    Visibility: public -/
def level.is_equiv
  (l : level.Level) (r : level.Level) : Result (Option Bool) := do
  let b ← level.beq l r
  if b
  then ok (some true)
  else
    let l1 ← level.simplify l
    let l2 ← level.simplify r
    let b1 ← level.beq l1 l2
    if b1
    then ok (some true)
    else
      let o ← level.leq l r
      match o with
      | none => ok none
      | some b2 => if b2
                   then level.leq r l
                   else ok o

/-- [level_name::level::is_equiv_list_from]:
    Source: 'src/level.rs', lines 431:0-443:1
    Visibility: public -/
def level.is_equiv_list_from
  (ls : alloc.vec.Vec level.Level) (rs : alloc.vec.Vec level.Level)
  (i : Std.Usize) :
  Result (Option Bool)
  := do
  let i1 := alloc.vec.Vec.len ls
  if i >= i1
  then
    let i2 := alloc.vec.Vec.len rs
    if i >= i2
    then ok (some true)
    else
      let i3 := alloc.vec.Vec.len ls
      if i >= i3
      then ok (some false)
      else
        let i4 := alloc.vec.Vec.len rs
        if i >= i4
        then ok (some false)
        else
          let l ←
            alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice
              level.Level) ls i
          let l1 ←
            alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice
              level.Level) rs i
          let o ← level.is_equiv l l1
          match o with
          | none => ok none
          | some b =>
            if b
            then let i5 ← i + 1#usize
                 level.is_equiv_list_from ls rs i5
            else ok o
  else
    let i2 := alloc.vec.Vec.len ls
    if i >= i2
    then ok (some false)
    else
      let i3 := alloc.vec.Vec.len rs
      if i >= i3
      then ok (some false)
      else
        let l ←
          alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice
            level.Level) ls i
        let l1 ←
          alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice
            level.Level) rs i
        let o ← level.is_equiv l l1
        match o with
        | none => ok none
        | some b =>
          if b
          then let i4 ← i + 1#usize
               level.is_equiv_list_from ls rs i4
          else ok o
partial_fixpoint

/-- [level_name::level::is_equiv_list]:
    Source: 'src/level.rs', lines 426:0-428:1
    Visibility: public -/
def level.is_equiv_list
  (ls : alloc.vec.Vec level.Level) (rs : alloc.vec.Vec level.Level) :
  Result (Option Bool)
  := do
  level.is_equiv_list_from ls rs 0#usize

/-- [level_name::level::is_zero]:
    Source: 'src/level.rs', lines 446:0-448:1
    Visibility: public -/
def level.is_zero (l : level.Level) : Result Bool := do
  let l1 ← level.simplify l
  level.is_zero_kind l1

/-- [level_name::level::is_non_zero]:
    Source: 'src/level.rs', lines 451:0-459:1
    Visibility: public -/
def level.is_non_zero (u : level.Level) : Result Bool := do
  let ln ← alloc.rc.Rc.Insts.CoreOpsDerefDeref.deref Global u._0
  match ln.kind with
  | level.LevelKind.Zero => ok false
  | level.LevelKind.Succ _ => ok true
  | level.LevelKind.Max a b =>
    let b1 ← level.is_non_zero a
    if b1
    then ok true
    else level.is_non_zero b
  | level.LevelKind.Imax _ b => level.is_non_zero b
  | level.LevelKind.Param _ => ok false
partial_fixpoint

/-- [level_name::level::name_nodup_from]:
    Source: 'src/level.rs', lines 472:0-480:1
    Visibility: public -/
def level.name_nodup_from
  (ns : alloc.vec.Vec name.Name) (i : Std.Usize) : Result Bool := do
  let i1 := alloc.vec.Vec.len ns
  if i >= i1
  then ok true
  else
    let i2 ← i + 1#usize
    let n ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice name.Name) ns
        i
    let b ← name.contains_from ns i2 n
    if b
    then ok false
    else level.name_nodup_from ns i2
partial_fixpoint

/-- [level_name::level::name_nodup]:
    Source: 'src/level.rs', lines 467:0-469:1
    Visibility: public -/
def level.name_nodup (ns : alloc.vec.Vec name.Name) : Result Bool := do
  level.name_nodup_from ns 0#usize

/-- [level_name::level::is_model_str]:
    Source: 'src/level.rs', lines 493:0-501:1
    Visibility: public -/
def level.is_model_str (s : alloc.vec.Vec Std.U32) : Result Bool := do
  let i := alloc.vec.Vec.len s
  if i = 6#usize
  then
    let i1 ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice Std.U32) s
        0#usize
    if i1 = 95#u32
    then
      let i2 ←
        alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice Std.U32) s
          1#usize
      if i2 = 109#u32
      then
        let i3 ←
          alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice Std.U32) s
            2#usize
        if i3 = 111#u32
        then
          let i4 ←
            alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice Std.U32)
              s 3#usize
          if i4 = 100#u32
          then
            let i5 ←
              alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice
                Std.U32) s 4#usize
            if i5 = 101#u32
            then
              let i6 ←
                alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice
                  Std.U32) s 5#usize
              ok (i6 = 108#u32)
            else ok false
          else ok false
        else ok false
      else ok false
    else ok false
  else ok false

/-- [level_name::level::name_is_model_suffix]:
    Source: 'src/level.rs', lines 485:0-490:1
    Visibility: public -/
def level.name_is_model_suffix (n : name.Name) : Result Bool := do
  let nn ← alloc.rc.Rc.Insts.CoreOpsDerefDeref.deref Global n._0
  match nn.kind with
  | name.NameKind.Anonymous => ok false
  | name.NameKind.Str _ s => level.is_model_str s
  | name.NameKind.Num _ _ => ok false

/-- [level_name::level::is_proj_str]:
    Source: 'src/level.rs', lines 504:0-506:1
    Visibility: public -/
def level.is_proj_str (s : alloc.vec.Vec Std.U32) : Result Bool := do
  let i := alloc.vec.Vec.len s
  if i = 4#usize
  then
    let i1 ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice Std.U32) s
        0#usize
    if i1 = 112#u32
    then
      let i2 ←
        alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice Std.U32) s
          1#usize
      if i2 = 114#u32
      then
        let i3 ←
          alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice Std.U32) s
            2#usize
        if i3 = 111#u32
        then
          let i4 ←
            alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice Std.U32)
              s 3#usize
          ok (i4 = 106#u32)
        else ok false
      else ok false
    else ok false
  else ok false

/-- [level_name::level::is_proj_table_str]:
    Source: 'src/level.rs', lines 509:0-520:1
    Visibility: public -/
def level.is_proj_table_str (s : alloc.vec.Vec Std.U32) : Result Bool := do
  let i := alloc.vec.Vec.len s
  if i = 9#usize
  then
    let i1 ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice Std.U32) s
        0#usize
    if i1 = 112#u32
    then
      let i2 ←
        alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice Std.U32) s
          1#usize
      if i2 = 114#u32
      then
        let i3 ←
          alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice Std.U32) s
            2#usize
        if i3 = 111#u32
        then
          let i4 ←
            alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice Std.U32)
              s 3#usize
          if i4 = 106#u32
          then
            let i5 ←
              alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice
                Std.U32) s 4#usize
            if i5 = 84#u32
            then
              let i6 ←
                alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice
                  Std.U32) s 5#usize
              if i6 = 97#u32
              then
                let i7 ←
                  alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice
                    Std.U32) s 6#usize
                if i7 = 98#u32
                then
                  let i8 ←
                    alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice
                      Std.U32) s 7#usize
                  if i8 = 108#u32
                  then
                    let i9 ←
                      alloc.vec.Vec.index
                        (core.slice.index.SliceIndexUsizeSlice Std.U32) s
                        8#usize
                    ok (i9 = 101#u32)
                  else ok false
                else ok false
              else ok false
            else ok false
          else ok false
        else ok false
      else ok false
    else ok false
  else ok false

/-- [level_name::level::name_is_proj_fn_shape]:
    Source: 'src/level.rs', lines 524:0-532:1
    Visibility: public -/
def level.name_is_proj_fn_shape (n : name.Name) : Result Bool := do
  let nn ← alloc.rc.Rc.Insts.CoreOpsDerefDeref.deref Global n._0
  match nn.kind with
  | name.NameKind.Anonymous => ok false
  | name.NameKind.Str _ _ => ok false
  | name.NameKind.Num p _ =>
    let nn1 ← alloc.rc.Rc.Insts.CoreOpsDerefDeref.deref Global p._0
    match nn1.kind with
    | name.NameKind.Anonymous => ok false
    | name.NameKind.Str _ s =>
      let b ← level.is_proj_str s
      if b
      then ok true
      else level.is_proj_table_str s
    | name.NameKind.Num _ _ => ok false

/-- [level_name::name::str_hash_from]:
    Source: 'src/name.rs', lines 54:0-60:1
    Visibility: public -/
def name.str_hash_from
  (s : alloc.vec.Vec Std.U32) (i : Std.Usize) (acc : Std.U64) :
  Result Std.U64
  := do
  let i1 := alloc.vec.Vec.len s
  if i >= i1
  then ok acc
  else
    let i2 ← i + 1#usize
    let i3 ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice Std.U32) s i
    let i4 ← lift (UScalar.cast .U64 i3)
    let i5 ← name.mix_hash acc i4
    name.str_hash_from s i2 i5
partial_fixpoint

/-- [level_name::name::str_hash]:
    Source: 'src/name.rs', lines 49:0-51:1
    Visibility: public -/
def name.str_hash (s : alloc.vec.Vec Std.U32) : Result Std.U64 := do
  name.str_hash_from s 0#usize 11#u64

/-- [level_name::name::nat_hash]:
    Source: 'src/name.rs', lines 64:0-66:1
    Visibility: public -/
def name.nat_hash (n : Std.U64) : Result Std.U64 := do
  ok n

/-- [level_name::name::anonymous]:
    Source: 'src/name.rs', lines 74:0-76:1
    Visibility: public -/
def name.anonymous : Result name.Name := do
  let r ← alloc.rc.Rc.new (name.NameNode.mk 1723#u64 name.NameKind.Anonymous)
  ok (name.Name.mk r)

/-- [level_name::name::mk_str]:
    Source: 'src/name.rs', lines 80:0-83:1
    Visibility: public -/
def name.mk_str
  (pre : name.Name) (s : alloc.vec.Vec Std.U32) : Result name.Name := do
  let i ← name.hash_data pre
  let i1 ← name.mix_hash 1#u64 i
  let i2 ← name.str_hash s
  let h ← name.mix_hash i1 i2
  let r ← alloc.rc.Rc.new (name.NameNode.mk h (name.NameKind.Str pre s))
  ok (name.Name.mk r)

/-- [level_name::name::mk_num]:
    Source: 'src/name.rs', lines 87:0-90:1
    Visibility: public -/
def name.mk_num (pre : name.Name) (n : Std.U64) : Result name.Name := do
  let i ← name.hash_data pre
  let i1 ← name.mix_hash 2#u64 i
  let i2 ← name.nat_hash n
  let h ← name.mix_hash i1 i2
  let r ← alloc.rc.Rc.new (name.NameNode.mk h (name.NameKind.Num pre n))
  ok (name.Name.mk r)

end level_name
