-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [level_name]: type definitions
import Aeneas
import LevelName.TypesExternal
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace level_name

/-- Trait declaration: [core::alloc::AllocatorClone]
    Source: '/rustc/library/core/src/alloc/mod.rs', lines 531:0-531:50
    Name pattern: [core::alloc::AllocatorClone]
    Visibility: public -/
@[rust_trait "core::alloc::AllocatorClone"
  (parentClauses := ["cloneCloneInst"])]
structure core.alloc.AllocatorClone (Self : Type) where
  cloneCloneInst : core.clone.Clone Self

mutual

/-- [level_name::name::NameKind]
    Source: 'src/name.rs', lines 16:0-20:1
    Visibility: public -/
@[discriminant isize]
inductive name.NameKind where
| Anonymous : name.NameKind
| Str : name.Name → alloc.vec.Vec Std.U32 → name.NameKind
| Num : name.Name → Std.U64 → name.NameKind

/-- [level_name::name::NameNode]
    Source: 'src/name.rs', lines 24:0-27:1
    Visibility: public -/
inductive name.NameNode where
| mk : Std.U64 → name.NameKind → name.NameNode

/-- [level_name::name::Name]
    Source: 'src/name.rs', lines 30:0-30:34
    Visibility: public -/
inductive name.Name where
| mk : alloc.rc.Rc name.NameNode → name.Name

end

def name.NameNode.hash (x : name.NameNode) :=
  match x with | name.NameNode.mk x1 _ => x1

def name.NameNode.kind (x : name.NameNode) :=
  match x with | name.NameNode.mk _ x1 => x1

@[simp]
theorem name.NameNode.hash._simpLemma_ (hash : Std.U64) (kind : name.NameKind)
  : (name.NameNode.mk hash kind).hash = hash := by rfl

@[simp]
theorem name.NameNode.kind._simpLemma_ (hash : Std.U64) (kind : name.NameKind)
  : (name.NameNode.mk hash kind).kind = kind := by rfl

def name.Name._0 (x : name.Name) := match x with | name.Name.mk x1 => x1

@[simp]
theorem name.Name._0._simpLemma_ (_0 : alloc.rc.Rc name.NameNode) :
  (name.Name.mk _0)._0 = _0 := by rfl

mutual

/-- [level_name::level::LevelKind]
    Source: 'src/level.rs', lines 18:0-24:1
    Visibility: public -/
@[discriminant isize]
inductive level.LevelKind where
| Zero : level.LevelKind
| Succ : level.Level → level.LevelKind
| Max : level.Level → level.Level → level.LevelKind
| Imax : level.Level → level.Level → level.LevelKind
| Param : name.Name → level.LevelKind

/-- [level_name::level::LevelNode]
    Source: 'src/level.rs', lines 28:0-31:1
    Visibility: public -/
inductive level.LevelNode where
| mk : Std.U64 → level.LevelKind → level.LevelNode

/-- [level_name::level::Level]
    Source: 'src/level.rs', lines 34:0-34:36
    Visibility: public -/
inductive level.Level where
| mk : alloc.rc.Rc level.LevelNode → level.Level

end

def level.LevelNode.hash (x : level.LevelNode) :=
  match x with | level.LevelNode.mk x1 _ => x1

def level.LevelNode.kind (x : level.LevelNode) :=
  match x with | level.LevelNode.mk _ x1 => x1

@[simp]
theorem level.LevelNode.hash._simpLemma_ (hash : Std.U64) (kind :
  level.LevelKind) : (level.LevelNode.mk hash kind).hash = hash := by rfl

@[simp]
theorem level.LevelNode.kind._simpLemma_ (hash : Std.U64) (kind :
  level.LevelKind) : (level.LevelNode.mk hash kind).kind = kind := by rfl

def level.Level._0 (x : level.Level) := match x with | level.Level.mk x1 => x1

@[simp]
theorem level.Level._0._simpLemma_ (_0 : alloc.rc.Rc level.LevelNode) :
  (level.Level.mk _0)._0 = _0 := by rfl

end level_name
