-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [dup_tuple]: function definitions
import Aeneas
import DupTuple.Types
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace DupTuple

/-- [dup_tuple::{impl dup_tuple::Dup for u64}::dup2]:
    Source: 'src/lib.rs', lines 14:4-16:5
    Visibility: public -/
def U64.Insts.Dup_tupleDup.dup2 (self : Std.U64) : Result Std.U64 := do
  ok self

/-- Trait implementation: [dup_tuple::{impl dup_tuple::Dup for u64}]
    Source: 'src/lib.rs', lines 13:0-17:1 -/
@[reducible]
def U64.Insts.Dup_tupleDup : Dup Std.U64 := {
  dup2 := U64.Insts.Dup_tupleDup.dup2
}

/-- [dup_tuple::{impl dup_tuple::Dup for bool}::dup2]:
    Source: 'src/lib.rs', lines 20:4-22:5
    Visibility: public -/
def Bool.Insts.Dup_tupleDup.dup2 (self : Bool) : Result Bool := do
  ok self

/-- Trait implementation: [dup_tuple::{impl dup_tuple::Dup for bool}]
    Source: 'src/lib.rs', lines 19:0-23:1 -/
@[reducible]
def Bool.Insts.Dup_tupleDup : Dup Bool := {
  dup2 := Bool.Insts.Dup_tupleDup.dup2
}

/-- [dup_tuple::{impl dup_tuple::Dup for dup_tuple::Name}::dup2]:
    Source: 'src/lib.rs', lines 26:4-28:5
    Visibility: public -/
def Name.Insts.Dup_tupleDup.dup2 (self : Name) : Result Name := do
  ok self

/-- Trait implementation: [dup_tuple::{impl dup_tuple::Dup for dup_tuple::Name}]
    Source: 'src/lib.rs', lines 25:0-29:1 -/
@[reducible]
def Name.Insts.Dup_tupleDup : Dup Name := {
  dup2 := Name.Insts.Dup_tupleDup.dup2
}

/-- [dup_tuple::{impl dup_tuple::Dup for dup_tuple::Lvl}::dup2]:
    Source: 'src/lib.rs', lines 36:4-38:5
    Visibility: public -/
def Lvl.Insts.Dup_tupleDup.dup2 (self : Lvl) : Result Lvl := do
  ok self

/-- Trait implementation: [dup_tuple::{impl dup_tuple::Dup for dup_tuple::Lvl}]
    Source: 'src/lib.rs', lines 35:0-39:1 -/
@[reducible]
def Lvl.Insts.Dup_tupleDup : Dup Lvl := {
  dup2 := Lvl.Insts.Dup_tupleDup.dup2
}

/-- [dup_tuple::dup_vec_go]:
    Source: 'src/lib.rs', lines 48:0-56:1
    Visibility: public -/
def dup_vec_go
  (src : alloc.vec.Vec Lvl) (out : alloc.vec.Vec Lvl) (i : Std.Usize) :
  Result (alloc.vec.Vec Lvl)
  := do
  let i1 := alloc.vec.Vec.len src
  if i >= i1
  then ok out
  else
    let l ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice Lvl) src i
    let l1 ← Lvl.Insts.Dup_tupleDup.dup2 l
    let out1 ← alloc.vec.Vec.push out l1
    let i2 ← i + 1#usize
    dup_vec_go src out1 i2
partial_fixpoint

/-- [dup_tuple::{impl dup_tuple::Dup for alloc::vec::Vec<dup_tuple::Lvl>}::dup2]:
    Source: 'src/lib.rs', lines 43:4-45:5
    Visibility: public -/
def alloc.vec.VecLvl.Insts.Dup_tupleDup.dup2
  (self : alloc.vec.Vec Lvl) : Result (alloc.vec.Vec Lvl) := do
  dup_vec_go self (alloc.vec.Vec.new Lvl) 0#usize

/-- Trait implementation: [dup_tuple::{impl dup_tuple::Dup for alloc::vec::Vec<dup_tuple::Lvl>}]
    Source: 'src/lib.rs', lines 42:0-46:1 -/
@[reducible]
def alloc.vec.VecLvl.Insts.Dup_tupleDup : Dup (alloc.vec.Vec Lvl) := {
  dup2 := alloc.vec.VecLvl.Insts.Dup_tupleDup.dup2
}

/-- [dup_tuple::{impl dup_tuple::Dup for (A, B)}::dup2]:
    Source: 'src/lib.rs', lines 60:4-62:5
    Visibility: public -/
def Pair.Insts.Dup_tupleDup.dup2
  {A : Type} {B : Type} (DupInst : Dup A) (DupInst1 : Dup B) (self : (A × B))
  :
  Result (A × B)
  := do
  let (t, t1) := self
  let t2 ← DupInst.dup2 t
  let t3 ← DupInst1.dup2 t1
  ok (t2, t3)

/-- Trait implementation: [dup_tuple::{impl dup_tuple::Dup for (A, B)}]
    Source: 'src/lib.rs', lines 59:0-63:1 -/
@[reducible]
def Pair.Insts.Dup_tupleDup {A : Type} {B : Type} (DupInst : Dup A) (DupInst1 :
  Dup B) : Dup (A × B) := {
  dup2 := Pair.Insts.Dup_tupleDup.dup2 DupInst DupInst1
}

/-- [dup_tuple::{impl dup_tuple::Dup for (A, B, C)}::dup2]:
    Source: 'src/lib.rs', lines 67:4-69:5
    Visibility: public -/
def TupleABC.Insts.Dup_tupleDup.dup2
  {A : Type} {B : Type} {C : Type} (DupInst : Dup A) (DupInst1 : Dup B)
  (DupInst2 : Dup C) (self : (A × B × C)) :
  Result (A × B × C)
  := do
  let (t, t1, t2) := self
  let t3 ← DupInst.dup2 t
  let t4 ← DupInst1.dup2 t1
  let t5 ← DupInst2.dup2 t2
  ok (t3, t4, t5)

/-- Trait implementation: [dup_tuple::{impl dup_tuple::Dup for (A, B, C)}]
    Source: 'src/lib.rs', lines 66:0-70:1 -/
@[reducible]
def TupleABC.Insts.Dup_tupleDup {A : Type} {B : Type} {C : Type} (DupInst : Dup
  A) (DupInst1 : Dup B) (DupInst2 : Dup C) : Dup (A × B × C) := {
  dup2 := TupleABC.Insts.Dup_tupleDup.dup2 DupInst DupInst1 DupInst2
}

/-- [dup_tuple::dup_alist]:
    Source: 'src/lib.rs', lines 83:0-91:1
    Visibility: public -/
def dup_alist
  {K : Type} {V : Type} (DupInst : Dup K) (DupInst1 : Dup V) (l : AList K V) :
  Result (AList K V)
  := do
  match l with
  | AList.Nil => ok AList.Nil
  | AList.Cons k v tl =>
    match tl with
    | none =>
      let t ← DupInst.dup2 k
      let t1 ← DupInst1.dup2 v
      ok (AList.Cons t t1 none)
    | some t =>
      let t1 ← DupInst.dup2 k
      let t2 ← DupInst1.dup2 v
      let a ← dup_alist DupInst DupInst1 t
      ok (AList.Cons t1 t2 (some a))
partial_fixpoint

/-- [dup_tuple::dup_slots]:
    Source: 'src/lib.rs', lines 93:0-99:1
    Visibility: public -/
def dup_slots
  {K : Type} {V : Type} (DupInst : Dup K) (DupInst1 : Dup V)
  (src : alloc.vec.Vec (AList K V)) (out : alloc.vec.Vec (AList K V))
  (i : Std.Usize) :
  Result (alloc.vec.Vec (AList K V))
  := do
  let i1 := alloc.vec.Vec.len src
  if i >= i1
  then ok out
  else
    let a ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice (AList K V))
        src i
    let a1 ← dup_alist DupInst DupInst1 a
    let out1 ← alloc.vec.Vec.push out a1
    let i2 ← i + 1#usize
    dup_slots DupInst DupInst1 src out1 i2
partial_fixpoint

/-- [dup_tuple::dup_table]:
    Source: 'src/lib.rs', lines 101:0-105:1
    Visibility: public -/
def dup_table
  {K : Type} {V : Type} (DupInst : Dup K) (DupInst1 : Dup V) (t : Table K V) :
  Result (Table K V)
  := do
  let slots ←
    dup_slots DupInst DupInst1 t.slots (alloc.vec.Vec.new (AList K V)) 0#usize
  ok { t with slots }

/-- [dup_tuple::dup_pair_table]:
    Source: 'src/lib.rs', lines 108:0-110:1
    Visibility: public -/
def dup_pair_table
  (t : Table (Name × (alloc.vec.Vec Lvl)) Std.U64) :
  Result (Table (Name × (alloc.vec.Vec Lvl)) Std.U64)
  := do
  dup_table (Pair.Insts.Dup_tupleDup Name.Insts.Dup_tupleDup
    alloc.vec.VecLvl.Insts.Dup_tupleDup) U64.Insts.Dup_tupleDup t

/-- [dup_tuple::dup_triple_table]:
    Source: 'src/lib.rs', lines 112:0-114:1
    Visibility: public -/
def dup_triple_table
  (t : Table (Name × Name × (alloc.vec.Vec Lvl)) Bool) :
  Result (Table (Name × Name × (alloc.vec.Vec Lvl)) Bool)
  := do
  dup_table (TupleABC.Insts.Dup_tupleDup Name.Insts.Dup_tupleDup
    Name.Insts.Dup_tupleDup alloc.vec.VecLvl.Insts.Dup_tupleDup)
    Bool.Insts.Dup_tupleDup t

end DupTuple
