-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [dup_tuple]: type definitions
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace DupTuple

/-- Trait declaration: [dup_tuple::Dup]
    Source: 'src/lib.rs', lines 5:0-7:1
    Visibility: public -/
structure Dup (Self : Type) where
  dup2 : Self → Result Self

/-- [dup_tuple::Name]
    Source: 'src/lib.rs', lines 9:0-11:1
    Visibility: public -/
structure Name where
  w : Std.U64

/-- [dup_tuple::Lvl]
    Source: 'src/lib.rs', lines 31:0-33:1
    Visibility: public -/
structure Lvl where
  k : Std.U64

/-- [dup_tuple::AList]
    Source: 'src/lib.rs', lines 73:0-76:1
    Visibility: public -/
@[discriminant isize]
inductive AList (K : Type) (V : Type) where
| Nil : AList K V
| Cons : K → V → Option (AList K V) → AList K V

/-- [dup_tuple::Table]
    Source: 'src/lib.rs', lines 78:0-81:1
    Visibility: public -/
structure Table (K : Type) (V : Type) where
  slots : alloc.vec.Vec (AList K V)
  n : Std.Usize

end DupTuple
