//! `ConLeche/Cached/CheckerC.lean` — **the cached declaration driver**, or
//! rather the one part of it the knot rule leaves standing.
//!
//! The declaration checker *above* `CheckerOps` is shared verbatim between
//! con-leche's two lanes: only the core is replaced.  What the cited file adds
//! is (a) the entry-point record over the cached core — `opE`, `opB`, `opS`
//! and `sharedOpsC` — and (b) a per-declaration phase-driver layer for the
//! inductive installs.
//!
//! **(a) collapses entirely.**  `opE fe pick d e` is `pick (coreKnotI mode fe
//! checkFuel) d e`: a *slot selector* passed as a function
//! (`(·.annotate)`, `(·.infer)`, `(·.whnf)`) into a record projection.
//! DESIGN.md §3.1's knot rule leaves no record to project and §3.4 forbids
//! the closure, so `sharedOpsC`'s five core slots are `core_c`'s wrappers
//! called by name at `check_fuel()` — spelled once, in
//! `crate::kernel::type_checker`, which cites this file's `sharedOpsC` for
//! exactly that reason.  `opB`/`opS` are the same collapse for `defeq` and
//! `ensureSortI`.
//!
//! **(b) is not ported yet.**  `checkIndMemberS`, `provisionRecsS`,
//! `checkIndRecsS`, `checkProjFnS`, `installProjFnStepS`, `checkNativePassS`,
//! `checkNativeTailS`, `checkNativeS`, `checkIndDeclSF` and the three
//! memoised direct-install walkers (`instPisAtLiftC`, `structProjBodiesGoC`,
//! `structProjBodiesC`, `structWalkersC`) all stand on
//! `ConLeche/Kernel/Inductives/*` — `NativeParts`, `StructWalkers`,
//! `checkSumIndF`, `checkNativeRecF`, `constsResolveFC`, … — a family this
//! task does not port.  They are recorded here so the next porter does not
//! re-derive the list.
//!
//! ## What *is* here: `orElse`, the one variant-fallback point
//!
//! `CheckerOps.orElse` (`Kernel/CheckerBase.lean:36-53`) runs an attempt; on
//! `true` the whole is `pure ()`; on `false` **or on an error** the
//! continuation runs, told the outcome (`none` after `false`, `some e` after
//! an error) for diagnostic text only.  It is con-leche's only place the
//! checker recovers from a thrown error, and it is scoped to exactly one
//! attempt: the Nat-op pin gate's per-variant `checkDivModPinAt`, where a
//! certificate blob generated by another toolchain can be ill-typed against
//! this stream — that is "this variant does not match", not a checker bug.
//! The `Unit` result is what makes the combinator fuel-monotone.
//!
//! The **continuation** is a closure, which §3.4 forbids, so it stays at the
//! call site (`kernel::checker::check_div_mod_pin_loop`'s own tail call — task
//! #18's treatment of `whnfStep`'s continuation) and what is ported here is
//! the combinator's *decision*: the three-way `OrElseStep`.  The pure
//! instantiations (`fueledOps`) hand the continuation `none` regardless,
//! because a fuel-indexed family cannot carry an outcome that differs between
//! fuels; the executable's `sharedOpsC` delivers it.
//!
//! ### Task #67: the port backtracks, except on its own failures
//!
//! The port **recovers**, as the cited code does, and the one place it cannot
//! is the one place con-leche has no counterpart for.  `or_else_step` is
//! four-way:
//!
//! ```text
//! | .ok (true,  s') => .ok ((), s')     ->  Matched
//! | .ok (false, s') => k none      s'   ->  Continue    (post-attempt state)
//! | .error e        => k (some e)  s    ->  Recovered(e) (PRE-attempt state)
//!                                      ->  Failed(e)    when e is `Native`
//! ```
//!
//! `Recovered(e)` is the cited `k (some e) s`: the caller
//! (`kernel::checker::check_div_mod_pin_loop`) restores the **pre-attempt**
//! `CState` from a `cached::state_c::dup` snapshot -- "the memo entries the
//! failed attempt wrote are discarded with it" -- and moves to the next
//! variant carrying `e`'s message for the decline text, which is what
//! `divModAttemptReason ps (some e)` renders into the accumulator.  Only
//! `Ok(false)` moves on with the attempt's own state, which is the cited
//! `false` arm.
//!
//! `Failed(e)` is the port's own arm and carries **only** a
//! `CheckError::Native` (DESIGN.md 3's ruling of 2026-09-13): a machine-word
//! limit or a width check has no `throw` behind it, so "con-leche would have
//! recovered from this too" is a claim about a run the cited checker never
//! has.  The port declines the stream instead of guessing.  It is a
//! documented accept-direction deviation, it can only *lose* acceptances, and
//! 1's soundness claim is untouched.  This supersedes task #65's ruling,
//! under which *every* thrown attempt was the verdict.
//!
//! What the recovery costs is the snapshot -- `state_c::dup`, `O(size)`, taken
//! once per attempt whose guards pass, i.e. a handful of times in a run -- and
//! what it buys is that the port's pin loop *is* the cited loop, so the
//! refinement lemma follows from the full-outcome attempt lemma with no
//! hypothesis (task #65 had two, `OrElseErrorStateSound` and
//! `OrElseErrorDeclines`; task #67 has none, and the arm is reachable again).
//!
use crate::kernel::core_types::{CheckError, CheckM};

/// con-leche: ConLeche/Kernel/CheckerBase.lean:25-53 CheckerOps
/// con-leche: ConLeche/Cached/CheckerC.lean:81-96 sharedOpsC
/// What `orElse` decides, once the attempt has run: `Matched` is the cited
/// `pure ()`, `Continue` is the cited `k none s'` (the next variant, at the
/// attempt's own state), `Recovered(e)` the cited `k (some e) s` (the next
/// variant, at the **pre-attempt** state, carrying `e` for the decline text)
/// and `Failed(e)` the port's own fourth arm (module note): a `Native` error
/// has no cited `throw` to recover from, so it is the verdict.
pub enum OrElseStep {
    Matched,
    Continue,
    Recovered(CheckError),
    Failed(CheckError),
}

/// con-leche: ConLeche/Cached/CheckerC.lean:81-96 sharedOpsC
/// con-leche: ConLeche/Kernel/CheckerBase.lean:57-66 fueledOps
/// **`orElse`, the variant-fallback point.**  The cited match, clause for
/// clause, with the error clause split in two (task #67, module note):
///
/// ```text
/// | .ok (true,  s') => .ok ((), s')     ->  Matched
/// | .ok (false, s') => k none      s'   ->  Continue
/// | .error e        => k (some e)  s    ->  Recovered(e), or Failed(e)
///                                          when `e` is the port's own
///                                          `Native` (no cited `throw`)
/// ```
///
/// The continuation `k` is the caller's tail call and the state is threaded
/// through `&mut CState` (the caller restores the pre-attempt snapshot on
/// `Recovered`), so neither appears here.  `fueledOps`' clause is the cited
/// one with `none` in place of `some e`; the deviation is the same against
/// both.
pub fn or_else_step(attempt: CheckM<bool>) -> OrElseStep {
    match attempt {
        Ok(true) => OrElseStep::Matched,
        Ok(false) => OrElseStep::Continue,
        Err(e) => match e {
            CheckError::Native(m) => OrElseStep::Failed(CheckError::Native(m)),
            _ => OrElseStep::Recovered(e),
        },
    }
}

#[cfg(test)]
mod tests {
    use crate::cached::checker_c;
    use crate::cached::checker_c::OrElseStep;
    use crate::kernel::core_types;
    use crate::kernel::core_types::CheckError;

    /// **`orElse`, the variant-fallback point**, at its four outcomes: a
    /// successful attempt is the whole (`pure ()`); a `false` runs the
    /// continuation at the attempt's own state; a *mirrored* thrown error
    /// runs it too, at the pre-attempt state, carrying the error for the
    /// decline text (the cited `k (some e) s`, task #67); and the port's own
    /// `Native` error -- which no cited `throw` stands behind -- is the
    /// verdict.
    #[test]
    fn or_else_recovers_from_a_mirrored_error_and_fails_on_a_native_one() {
        match checker_c::or_else_step(Ok(true)) {
            OrElseStep::Matched => (),
            _ => panic!("a matched attempt is the whole"),
        }
        match checker_c::or_else_step(Ok(false)) {
            OrElseStep::Continue => (),
            _ => panic!("a `false` attempt must continue"),
        }
        let e: CheckError = core_types::not_implemented(core_types::code_points(&[110, 111]));
        match checker_c::or_else_step(Err(e)) {
            OrElseStep::Recovered(err) => {
                // the error travels out so the decline names what the
                // variant failed on, exactly as `divModAttemptReason` does
                assert!(core_types::beq(
                    &err,
                    &core_types::not_implemented(core_types::code_points(&[110, 111]))
                ));
            }
            _ => panic!("a mirrored error is recovered from, not the verdict"),
        }
        // an `internal` error is recovered from just the same: the cited
        // `orElse` does not look at the kind
        let e2: CheckError = core_types::internal(core_types::code_points(&[120]));
        match checker_c::or_else_step(Err(e2)) {
            OrElseStep::Recovered(_) => (),
            _ => panic!("a mirrored error is recovered from"),
        }
        let e3: CheckError = core_types::invalid(core_types::code_points(&[121]));
        match checker_c::or_else_step(Err(e3)) {
            OrElseStep::Recovered(_) => (),
            _ => panic!("a mirrored error is recovered from"),
        }
        // the port's own failure is the verdict: there is no cited `throw`
        // to recover from
        let e4: CheckError = core_types::native(core_types::code_points(&[122]));
        match checker_c::or_else_step(Err(e4)) {
            OrElseStep::Failed(err) => {
                assert!(core_types::beq(
                    &err,
                    &core_types::native(core_types::code_points(&[122]))
                ));
            }
            _ => panic!("a native error is the verdict"),
        }
    }
}
