//! `ConLeche/Cached/CheckerC.lean` — **the cached declaration driver**, or
//! rather the one part of it the knot rule leaves standing.
//!
//! The declaration checker *above* `CheckerOps` is shared verbatim between
//! con-leche's two lanes: only the core is replaced.  What the cited file adds
//! is (a) the entry-point record over the cached core — `opE`, `opB`, `opS`
//! and `sharedOpsC` — and (b) a per-declaration phase-driver layer for the
//! inductive installs.
//!
//! **(a) collapses entirely.**  `opE fe pick d e` is `pick (coreKnotI mode fe
//! checkFuel) d e`: a *slot selector* passed as a function
//! (`(·.annotate)`, `(·.infer)`, `(·.whnf)`) into a record projection.
//! DESIGN.md §3.1's knot rule leaves no record to project and §3.4 forbids
//! the closure, so `sharedOpsC`'s five core slots are `core_c`'s wrappers
//! called by name at `check_fuel()` — spelled once, in
//! `crate::kernel::type_checker`, which cites this file's `sharedOpsC` for
//! exactly that reason.  `opB`/`opS` are the same collapse for `defeq` and
//! `ensureSortI`.
//!
//! **(b) is not ported yet.**  `checkIndMemberS`, `provisionRecsS`,
//! `checkIndRecsS`, `checkProjFnS`, `installProjFnStepS`, `checkNativePassS`,
//! `checkNativeTailS`, `checkNativeS`, `checkIndDeclSF` and the three
//! memoised direct-install walkers (`instPisAtLiftC`, `structProjBodiesGoC`,
//! `structProjBodiesC`, `structWalkersC`) all stand on
//! `ConLeche/Kernel/Inductives/*` — `NativeParts`, `StructWalkers`,
//! `checkSumIndF`, `checkNativeRecF`, `constsResolveFC`, … — a family this
//! task does not port.  They are recorded here so the next porter does not
//! re-derive the list.
//!
//! ## What *is* here: `orElse`, the one variant-fallback point
//!
//! `CheckerOps.orElse` (`Kernel/CheckerBase.lean:36-53`) runs an attempt; on
//! `true` the whole is `pure ()`; on `false` **or on an error** the
//! continuation runs, told the outcome (`none` after `false`, `some e` after
//! an error) for diagnostic text only.  It is con-leche's only place the
//! checker recovers from a thrown error, and it is scoped to exactly one
//! attempt: the Nat-op pin gate's per-variant `checkDivModPinAt`, where a
//! certificate blob generated by another toolchain can be ill-typed against
//! this stream — that is "this variant does not match", not a checker bug.
//! The `Unit` result is what makes the combinator fuel-monotone.
//!
//! The **continuation** is a closure, which §3.4 forbids, so it stays at the
//! call site (`kernel::checker::check_div_mod_pin_loop`'s own tail call — task
//! #18's treatment of `whnfStep`'s continuation) and what is ported here is
//! the combinator's *decision*: the three-way `OrElseStep`.  The pure
//! instantiations (`fueledOps`) hand the continuation `none` regardless,
//! because a fuel-indexed family cannot carry an outcome that differs between
//! fuels; the executable's `sharedOpsC` delivers it.
//!
//! ### Task #65's ruling: **an attempt's error is the verdict**
//!
//! The port does **not** recover: `or_else_step` maps `Err e` to
//! `Failed(e)`, and `check_div_mod_pin_loop` makes that the whole pin
//! check's result — the stream is declined with `e`, naming what the variant
//! failed on, exactly as con-leche's decline names it once every variant has
//! failed.  Only the `false` arm moves on to the next variant, and it moves
//! on with the attempt's own state, which is what the port's `&mut CState`
//! threads anyway.
//!
//! This is a deliberate, documented **accept-direction deviation** (DESIGN.md
//! §3, the deviations list).  It can only *lose* acceptances, never gain one:
//! the single stream shape it separates the two checkers on is one where
//! variant `i`'s pin is definitionally equal to the stored value but one of
//! its certificates throws, *and* a later variant `j > i` matches in full —
//! con-leche accepts by walking on, con-ron declines with variant `i`'s error.
//! A declined stream is never an unsound accept, so §1's soundness claim is
//! untouched, and the accept direction is now stated against exactly what the
//! port does.
//!
//! What it buys is the refinement proof: con-leche's error arm hands the
//! continuation the **pre-attempt** state (`k (some e) s` — "the memo entries
//! the failed attempt wrote are discarded with it") where the port's
//! `&mut CState` has already written them, and it takes that arm exactly when
//! *its* attempt throws, which the accept-direction tower (DESIGN.md §3.5)
//! cannot predict from a port-side throw.  Those were the two hypotheses
//! `Refine/CheckerC.lean` and `Refine/CheckerPins.lean` carried to the
//! capstones (`OrElseErrorStateSound`, `OrElseErrorDeclines`, packaged as
//! `DivModOrElse`).  With the error arm as the verdict, a port accept at
//! variant `j` means every earlier attempt returned `Ok(false)` — con-leche's
//! own `false` arm, states in step — so both are gone and the theorems are
//! hypothesis-free here.

use crate::kernel::core_types::{CheckError, CheckM};

/// con-leche: ConLeche/Kernel/CheckerBase.lean:25-53 CheckerOps
/// con-leche: ConLeche/Cached/CheckerC.lean:81-96 sharedOpsC
/// What `orElse` decides, once the attempt has run: `Matched` is the cited
/// `pure ()`, `Continue` is "run the continuation" and `Failed(e)` is the
/// port's ruling (module note) that a thrown error is the whole check's
/// verdict, where the cited code would continue carrying `some e`.
pub enum OrElseStep {
    Matched,
    Continue,
    Failed(CheckError),
}

/// con-leche: ConLeche/Cached/CheckerC.lean:81-96 sharedOpsC
/// con-leche: ConLeche/Kernel/CheckerBase.lean:57-66 fueledOps
/// **`orElse`, the variant-fallback point.**  The cited match, clause for
/// clause, with the third clause ruled (task #65, module note):
///
/// ```text
/// | .ok (true,  s') => .ok ((), s')     ->  Matched
/// | .ok (false, s') => k none      s'   ->  Continue
/// | .error e        => k (some e)  s    ->  Failed(e)   (the deviation)
/// ```
///
/// The continuation `k` is the caller's tail call and the state is threaded
/// through `&mut CState`, so neither appears here.  `fueledOps`' clause is
/// the cited one with `none` in place of `some e`; the port's is the same
/// deviation against both.
pub fn or_else_step(attempt: CheckM<bool>) -> OrElseStep {
    match attempt {
        Ok(true) => OrElseStep::Matched,
        Ok(false) => OrElseStep::Continue,
        Err(e) => OrElseStep::Failed(e),
    }
}

#[cfg(test)]
mod tests {
    use crate::cached::checker_c;
    use crate::cached::checker_c::OrElseStep;
    use crate::kernel::core_types;
    use crate::kernel::core_types::CheckError;

    /// **`orElse`, the variant-fallback point**, at its three outcomes: a
    /// successful attempt is the whole (`pure ()`); a `false` runs the
    /// continuation, i.e. the loop's next variant; and a *thrown error* is
    /// the verdict — the port's ruling (task #65), where the cited code runs
    /// the continuation carrying the error.  The error travels out so the
    /// decline names what the variant failed on.
    #[test]
    fn or_else_error_is_the_verdict() {
        match checker_c::or_else_step(Ok(true)) {
            OrElseStep::Matched => (),
            _ => panic!("a matched attempt is the whole"),
        }
        match checker_c::or_else_step(Ok(false)) {
            OrElseStep::Continue => (),
            _ => panic!("a `false` attempt must continue"),
        }
        let e: CheckError = core_types::not_implemented(core_types::code_points(&[110, 111]));
        match checker_c::or_else_step(Err(e)) {
            OrElseStep::Failed(err) => {
                // the error is the verdict, and it travels out: the decline
                // names what the variant failed on
                assert!(core_types::beq(
                    &err,
                    &core_types::not_implemented(core_types::code_points(&[110, 111]))
                ));
            }
            _ => panic!("a thrown error is the verdict, not a match or a continue"),
        }
        // an `internal` error is the verdict just the same: the ruling is
        // scoped to the attempt, not to a kind of error
        let e2: CheckError = core_types::internal(core_types::code_points(&[120]));
        match checker_c::or_else_step(Err(e2)) {
            OrElseStep::Failed(_) => (),
            _ => panic!("a thrown error is the verdict"),
        }
    }
}
