//! `ConLeche/Cached/CheckerC.lean` — **the cached declaration driver**, or
//! rather the one part of it the knot rule leaves standing.
//!
//! The declaration checker *above* `CheckerOps` is shared verbatim between
//! con-leche's two lanes: only the core is replaced.  What the cited file adds
//! is (a) the entry-point record over the cached core — `opE`, `opB`, `opS`
//! and `sharedOpsC` — and (b) a per-declaration phase-driver layer for the
//! inductive installs.
//!
//! **(a) collapses entirely.**  `opE fe pick d e` is `pick (coreKnotI mode fe
//! checkFuel) d e`: a *slot selector* passed as a function
//! (`(·.annotate)`, `(·.infer)`, `(·.whnf)`) into a record projection.
//! DESIGN.md §3.1's knot rule leaves no record to project and §3.4 forbids
//! the closure, so `sharedOpsC`'s five core slots are `core_c`'s wrappers
//! called by name at `check_fuel()` — spelled once, in
//! `crate::kernel::type_checker`, which cites this file's `sharedOpsC` for
//! exactly that reason.  `opB`/`opS` are the same collapse for `defeq` and
//! `ensureSortI`.
//!
//! **(b) is not ported yet.**  `checkIndMemberS`, `provisionRecsS`,
//! `checkIndRecsS`, `checkProjFnS`, `installProjFnStepS`, `checkNativePassS`,
//! `checkNativeTailS`, `checkNativeS`, `checkIndDeclSF` and the three
//! memoised direct-install walkers (`instPisAtLiftC`, `structProjBodiesGoC`,
//! `structProjBodiesC`, `structWalkersC`) all stand on
//! `ConLeche/Kernel/Inductives/*` — `NativeParts`, `StructWalkers`,
//! `checkSumIndF`, `checkNativeRecF`, `constsResolveFC`, … — a family this
//! task does not port.  They are recorded here so the next porter does not
//! re-derive the list.
//!
//! ## What *is* here: `orElse`, the one error-recovery point
//!
//! `CheckerOps.orElse` (`Kernel/CheckerBase.lean:36-53`) runs an attempt; on
//! `true` the whole is `pure ()`; on `false` **or on an error** the
//! continuation runs, told the outcome (`none` after `false`, `some e` after
//! an error) for diagnostic text only.  It is the only place the checker
//! recovers from a thrown error, and it is scoped to exactly one attempt: the
//! Nat-op pin gate's per-variant `checkDivModPinAt`, where a certificate blob
//! generated by another toolchain can be ill-typed against this stream — that
//! is "this variant does not match", not a checker bug.  The `Unit` result is
//! what makes the combinator fuel-monotone.
//!
//! The **continuation** is a closure, which §3.4 forbids, so it stays at the
//! call site (`kernel::checker::check_div_mod_pin_loop`'s own tail call — task
//! #18's treatment of `whnfStep`'s continuation) and what is ported here is
//! the combinator's *decision*: the `Result` match of `sharedOpsC.orElse`,
//! exactly as written, as the three-way `OrElseStep`.  The pure
//! instantiations (`fueledOps`) hand the continuation `none` regardless,
//! because a fuel-indexed family cannot carry an outcome that differs between
//! fuels; the executable's `sharedOpsC` delivers it, and this is the
//! executable's.
//!
//! ### The one memo-policy deviation in this task, flagged
//!
//! `sharedOpsC.orElse`'s error arm is `k (some e) s` — the **pre-attempt**
//! state: "the memo entries the failed attempt wrote are discarded with it".
//! The port's state is a `&mut CState`, so the attempt's writes are already
//! in place when `or_else_step` sees the `Err`, and the continuation runs on
//! the post-attempt state.  Every entry is a correct answer (the maps are
//! pure function caches), so no verdict changes — but it is a *hit where the
//! Lean misses*, which DESIGN.md §3.1 asks to be flagged rather than taken
//! silently.  Reconciling it means either a `CState` snapshot in
//! `cached::state_c` or an upstream note, and it must happen before any
//! `check_decl_refines` is stated against `checkDeclsPure`.

use crate::kernel::core_types::{CheckError, CheckM};

/// con-leche: ConLeche/Kernel/CheckerBase.lean:25-53 CheckerOps
/// con-leche: ConLeche/Cached/CheckerC.lean:81-96 sharedOpsC
/// What `orElse` decides, once the attempt has run: `Matched` is the cited
/// `pure ()` and `Continue r` is "run the continuation, told `r`".  A named
/// three-way result rather than a `Bool`, because the outcome the
/// continuation is handed is part of the combinator (module note).
pub enum OrElseStep {
    Matched,
    Continue(Option<CheckError>),
}

/// con-leche: ConLeche/Cached/CheckerC.lean:81-96 sharedOpsC
/// con-leche: ConLeche/Kernel/CheckerBase.lean:57-66 fueledOps
/// **`orElse`, the checker's one error-recovery point.**  The cited match,
/// clause for clause:
///
/// ```text
/// | .ok (true,  s') => .ok ((), s')     ->  Matched
/// | .ok (false, s') => k none      s'   ->  Continue(None)
/// | .error e        => k (some e)  s    ->  Continue(Some(e))
/// ```
///
/// The continuation `k` is the caller's tail call and the state is threaded
/// through `&mut CState`, so neither appears here; the state deviation in the
/// error arm is the module note's, and it is the only one.  `fueledOps`'
/// clause is the same three-way decision with `none` in place of `some e`.
pub fn or_else_step(attempt: CheckM<bool>) -> OrElseStep {
    match attempt {
        Ok(true) => OrElseStep::Matched,
        Ok(false) => OrElseStep::Continue(None),
        Err(e) => OrElseStep::Continue(Some(e)),
    }
}

#[cfg(test)]
mod tests {
    use crate::cached::checker_c;
    use crate::cached::checker_c::OrElseStep;
    use crate::kernel::core_types;
    use crate::kernel::core_types::CheckError;

    /// **`orElse`, the checker's one error-recovery point**, at its three
    /// outcomes: a successful attempt is the whole (`pure ()`); a `false`
    /// runs the continuation with no diagnosis; and — the point of the
    /// combinator — a *thrown error* also runs the continuation, carrying the
    /// error, instead of propagating.  That last clause is why a certificate
    /// blob from another toolchain reads as "this variant does not match"
    /// rather than as a checker bug.
    #[test]
    fn or_else_recovers_from_a_thrown_error() {
        match checker_c::or_else_step(Ok(true)) {
            OrElseStep::Matched => (),
            OrElseStep::Continue(_) => panic!("a matched attempt is the whole"),
        }
        match checker_c::or_else_step(Ok(false)) {
            OrElseStep::Matched => panic!("a `false` attempt must continue"),
            OrElseStep::Continue(r) => {
                assert!(r.is_none(), "a `false` carries no error to report")
            }
        }
        let e: CheckError = core_types::not_implemented(core_types::code_points(&[110, 111]));
        match checker_c::or_else_step(Err(e)) {
            OrElseStep::Matched => panic!("an error must not read as a match"),
            OrElseStep::Continue(r) => match r {
                Some(err) => {
                    // the continuation is told *which* error, for the decline
                    // message; `fueledOps` would hand it `none` here
                    assert!(core_types::beq(
                        &err,
                        &core_types::not_implemented(core_types::code_points(&[110, 111]))
                    ));
                }
                None => panic!("the error reaches the continuation"),
            },
        }
        // an `internal` error is recovered from just the same: the combinator
        // is scoped to the attempt, not to a kind of error
        let e2: CheckError = core_types::internal(core_types::code_points(&[120]));
        match checker_c::or_else_step(Err(e2)) {
            OrElseStep::Matched => panic!("an error must not read as a match"),
            OrElseStep::Continue(r) => assert!(r.is_some()),
        }
    }
}
