/-
The task-#3 scale spike (`spikes/level-name/`), elaborated: the Aeneas output
for the Rust port of `ConLeche/Kernel/Name.lean` and the `Level` half of
`ConLeche/Kernel/Expr.lean` + `ConLeche/Kernel/Level.lean`, with the `Rc`
models of DESIGN.md §3.2 and the abstraction functions onto con-leche.

`Types.lean` and `Funs.lean` are generated by `aeneas` and are not hand-edited
(the `import` lines are rewritten to this module path by
`scripts/extract.sh`'s eventual successor; today by hand, recorded in the
task-#4 log).
-/
import ConRon.Spike.LevelName.Types
import ConRon.Spike.LevelName.TypesExternal
import ConRon.Spike.LevelName.Funs
import ConRon.Spike.LevelName.FunsExternal
import ConRon.Spike.LevelName.Abs
