-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [level_name]: external types.
-- Holes filled by hand (con-ron): DESIGN.md §3.2, the `Rc` model.
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- DESIGN.md §3.2: an `Rc<T>` is modeled as its contents, exactly as Aeneas
   models `Box<T>` (which Charon erases outright).  Faithful because the port
   never uses `Rc::get_mut`, `Rc::make_mut`, `Weak` or interior mutability
   (the style lint gates this), so an `Rc` is an immutable owner and the
   sharing is invisible to the value.

   `@[reducible]` is not decoration: without it Lean's automatic `SizeOf`
   generation for the mutually recursive `Name`/`Level` node types fails
   ("failed to generate `SizeOf` instance for `NameKind`: type mismatch"),
   because it will not unfold a semireducible alias to find the recursive
   occurrence behind it.  (`abbrev`, or a one-field structure, work equally;
   the reducible `def` is the smallest change to DESIGN.md §3.2.) -/
/-- [alloc::rc::Rc]
    Source: '/rustc/library/alloc/src/rc.rs', lines 324:0-327:1
    Name pattern: [alloc::rc::Rc]
    Visibility: public -/
@[reducible, rust_type "alloc::rc::Rc"]
def alloc.rc.Rc (T : Type) : Type := T
