-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [rc_fuel]: function definitions
import Aeneas
import RcFuel.Types
import RcFuel.FunsExternal
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace rc_fuel

/-- Trait implementation: [alloc::alloc::{impl core::alloc::AllocatorClone for alloc::alloc::Global}]
    Source: '/rustc/library/alloc/src/alloc.rs', lines 62:0-62:50
    Name pattern: [core::alloc::AllocatorClone<alloc::alloc::Global>] -/
@[reducible, rust_trait_impl
  "core::alloc::AllocatorClone<alloc::alloc::Global>"]
def alloc.alloc.Global.Insts.CoreAllocAllocatorClone :
  core.alloc.AllocatorClone Global := {
  cloneCloneInst := core.core.clone.CloneGlobal
}

/-- [rc_fuel::{impl core::clone::Clone for rc_fuel::Expr}::clone]:
    Source: 'src/lib.rs', lines 4:9-4:14
    Visibility: public -/
def Expr.Insts.CoreCloneClone.clone (self : Expr) : Result Expr := do
  match self with
  | Expr.BVar __self_0 =>
    let i ← lift (core.clone.impls.CloneU64.clone __self_0)
    ok (Expr.BVar i)
  | Expr.App __self_0 __self_1 =>
    let r ←
      alloc.rc.Rc.Insts.CoreCloneClone.clone
        alloc.alloc.Global.Insts.CoreAllocAllocatorClone __self_0
    let r1 ←
      alloc.rc.Rc.Insts.CoreCloneClone.clone
        alloc.alloc.Global.Insts.CoreAllocAllocatorClone __self_1
    ok (Expr.App r r1)
  | Expr.Lam __self_0 =>
    let r ←
      alloc.rc.Rc.Insts.CoreCloneClone.clone
        alloc.alloc.Global.Insts.CoreAllocAllocatorClone __self_0
    ok (Expr.Lam r)

/-- Trait implementation: [rc_fuel::{impl core::clone::Clone for rc_fuel::Expr}]
    Source: 'src/lib.rs', lines 4:9-4:14 -/
@[reducible]
def Expr.Insts.CoreCloneClone : core.clone.Clone Expr := {
  clone := Expr.Insts.CoreCloneClone.clone
}

/-- [rc_fuel::mix_hash]:
    Source: 'src/lib.rs', lines 18:0-20:1
    Visibility: public -/
def mix_hash (a : Std.U64) (b : Std.U64) : Result Std.U64 := do
  let i ← lift (core.num.U64.wrapping_mul a 11400714819323198485#u64)
  let i1 ← lift (core.num.U64.wrapping_add i b)
  ok (core.num.U64.rotate_left i1 17#u32)

/-- [rc_fuel::mk_bvar]:
    Source: 'src/lib.rs', lines 22:0-24:1
    Visibility: public -/
def mk_bvar (i : Std.U64) : Result (alloc.rc.Rc Node) := do
  let i1 ← mix_hash 3#u64 i
  alloc.rc.Rc.new (Node.mk i1 (Expr.BVar i))

/-- [rc_fuel::mk_app]:
    Source: 'src/lib.rs', lines 25:0-28:1
    Visibility: public -/
def mk_app
  (f : alloc.rc.Rc Node) (a : alloc.rc.Rc Node) :
  Result (alloc.rc.Rc Node)
  := do
  let n ← alloc.rc.Rc.Insts.CoreOpsDerefDeref.deref Global f
  let n1 ← alloc.rc.Rc.Insts.CoreOpsDerefDeref.deref Global a
  let i ← mix_hash n.data n1.data
  let d ← mix_hash 17#u64 i
  alloc.rc.Rc.new (Node.mk d (Expr.App f a))

/-- [rc_fuel::mk_lam]:
    Source: 'src/lib.rs', lines 29:0-32:1
    Visibility: public -/
def mk_lam (b : alloc.rc.Rc Node) : Result (alloc.rc.Rc Node) := do
  let n ← alloc.rc.Rc.Insts.CoreOpsDerefDeref.deref Global b
  let d ← mix_hash 19#u64 n.data
  alloc.rc.Rc.new (Node.mk d (Expr.Lam b))

/-- [rc_fuel::ptr_eq]:
    Source: 'src/lib.rs', lines 35:0-37:1
    Visibility: public -/
def ptr_eq (a : alloc.rc.Rc Node) (b : alloc.rc.Rc Node) : Result Bool := do
  alloc.rc.Rc.ptr_eq Global a b

/-- [rc_fuel::beq]:
    Source: 'src/lib.rs', lines 39:0-52:1
    Visibility: public -/
def beq (a : alloc.rc.Rc Node) (b : alloc.rc.Rc Node) : Result Bool := do
  let b1 ← ptr_eq a b
  if b1
  then ok true
  else
    let n ← alloc.rc.Rc.Insts.CoreOpsDerefDeref.deref Global a
    let n1 ← alloc.rc.Rc.Insts.CoreOpsDerefDeref.deref Global b
    if n.data != n1.data
    then ok false
    else
      match n.expr with
      | Expr.BVar i =>
        match n1.expr with
        | Expr.BVar j => lift (core.cmp.impls.PartialEqU64.eq i j)
        | Expr.App _ _ => ok false
        | Expr.Lam _ => ok false
      | Expr.App f1 a1 =>
        match n1.expr with
        | Expr.BVar _ => ok false
        | Expr.App f2 a2 =>
          let b2 ← beq f1 f2
          if b2
          then beq a1 a2
          else ok false
        | Expr.Lam _ => ok false
      | Expr.Lam b11 =>
        match n1.expr with
        | Expr.BVar _ => ok false
        | Expr.App _ _ => ok false
        | Expr.Lam b2 => beq b11 b2
partial_fixpoint

/-- [rc_fuel::memo_find]: loop body 0:
    Source: 'src/lib.rs', lines 62:4-69:1
    Visibility: public -/
@[rust_loop_body]
def memo_find_loop.body
  (m : Memo) (k : alloc.rc.Rc Node) (i : Std.Usize) :
  Result (ControlFlow Std.Usize (Option Std.U64))
  := do
  let i1 := alloc.vec.Vec.len m.entries
  if i < i1
  then
    let (r, i2) ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice ((alloc.rc.Rc
        Node) × Std.U64)) m.entries i
    let b ← beq r k
    if b
    then ok (done (some i2))
    else let i3 ← i + 1#usize
         ok (cont i3)
  else ok (done none)

/-- [rc_fuel::memo_find]: loop 0:
    Source: 'src/lib.rs', lines 62:4-69:1
    Visibility: public -/
@[rust_loop]
def memo_find_loop
  (m : Memo) (k : alloc.rc.Rc Node) (i : Std.Usize) :
  Result (Option Std.U64)
  := do
  loop
    (fun i1 => memo_find_loop.body m k i1)
    i

/-- [rc_fuel::memo_find]:
    Source: 'src/lib.rs', lines 60:0-69:1
    Visibility: public -/
@[reducible]
def memo_find (m : Memo) (k : alloc.rc.Rc Node) : Result (Option Std.U64) := do
  memo_find_loop m k 0#usize

/-- [rc_fuel::{impl core::clone::Clone for rc_fuel::CheckError}::clone]:
    Source: 'src/lib.rs', lines 71:9-71:14
    Visibility: public -/
def CheckError.Insts.CoreCloneClone.clone
  (self : CheckError) : Result CheckError := do
  ok self

/-- Trait implementation: [rc_fuel::{impl core::clone::Clone for rc_fuel::CheckError}]
    Source: 'src/lib.rs', lines 71:9-71:14 -/
@[reducible]
def CheckError.Insts.CoreCloneClone : core.clone.Clone CheckError := {
  clone := CheckError.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [rc_fuel::{impl core::marker::Copy for rc_fuel::CheckError}]
    Source: 'src/lib.rs', lines 71:16-71:20 -/
@[reducible]
def CheckError.Insts.CoreMarkerCopy : core.marker.Copy CheckError := {
  cloneInst := CheckError.Insts.CoreCloneClone
}

/-- Trait implementation: [rc_fuel::{impl core::marker::StructuralPartialEq for rc_fuel::CheckError}]
    Source: 'src/lib.rs', lines 71:22-71:31 -/
@[reducible]
def CheckError.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq CheckError := {
}

/-- [rc_fuel::{impl core::cmp::PartialEq<rc_fuel::CheckError> for rc_fuel::CheckError}::eq]:
    Source: 'src/lib.rs', lines 71:22-71:31
    Visibility: public -/
def CheckError.Insts.CoreCmpPartialEqCheckError.eq
  (self : CheckError) (other : CheckError) : Result Bool := do
  let self1 := read_discriminant self
  let other1 := read_discriminant other
  ok (self1 = other1)

/-- Trait implementation: [rc_fuel::{impl core::cmp::PartialEq<rc_fuel::CheckError> for rc_fuel::CheckError}]
    Source: 'src/lib.rs', lines 71:22-71:31 -/
@[reducible]
def CheckError.Insts.CoreCmpPartialEqCheckError : core.cmp.PartialEq CheckError
  CheckError := {
  eq := CheckError.Insts.CoreCmpPartialEqCheckError.eq
}

/-- [rc_fuel::{impl core::cmp::Eq for rc_fuel::CheckError}::assert_fields_are_eq]:
    Source: 'src/lib.rs', lines 71:33-71:35
    Visibility: public -/
def CheckError.Insts.CoreCmpEq.assert_fields_are_eq
  (self : CheckError) : Result Unit := do
  ok ()

/-- Trait implementation: [rc_fuel::{impl core::cmp::Eq for rc_fuel::CheckError}]
    Source: 'src/lib.rs', lines 71:33-71:35 -/
@[reducible]
def CheckError.Insts.CoreCmpEq : core.cmp.Eq CheckError := {
  partialEqInst := CheckError.Insts.CoreCmpPartialEqCheckError
  assert_fields_are_eq := CheckError.Insts.CoreCmpEq.assert_fields_are_eq
}

mutual

/-- [rc_fuel::size]:
    Source: 'src/lib.rs', lines 78:0-89:1
    Visibility: public -/
def size
  (fuel : Std.U64) (st : Memo) (e : alloc.rc.Rc Node) :
  Result ((core.result.Result Std.U64 CheckError) × Memo)
  := do
  if fuel = 0#u64
  then ok (core.result.Result.Err CheckError.FuelExhausted, st)
  else
    let o ← memo_find st e
    match o with
    | none =>
      let i ← fuel - 1#u64
      let (r, st1) ← size_core i st e
      let cf ← core.result.Result.Insts.CoreOpsTry.branch r
      match cf with
      | core.ops.control_flow.ControlFlow.Continue val =>
        let r1 ←
          alloc.rc.Rc.Insts.CoreCloneClone.clone
            alloc.alloc.Global.Insts.CoreAllocAllocatorClone e
        let v ← alloc.vec.Vec.push st1.entries (r1, val)
        ok (core.result.Result.Ok val, { st1 with entries := v })
      | core.ops.control_flow.ControlFlow.Break residual =>
        let r1 ←
          core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
            Std.U64 (core.convert.FromSame CheckError) residual
        ok (r1, st1)
    | some v =>
      let i ← st.hits + 1#u64
      ok (core.result.Result.Ok v, { st with hits := i })
partial_fixpoint

/-- [rc_fuel::size_core]:
    Source: 'src/lib.rs', lines 91:0-113:1
    Visibility: public -/
def size_core
  (fuel : Std.U64) (st : Memo) (e : alloc.rc.Rc Node) :
  Result ((core.result.Result Std.U64 CheckError) × Memo)
  := do
  let n ← alloc.rc.Rc.Insts.CoreOpsDerefDeref.deref Global e
  match n.expr with
  | Expr.BVar _ => ok (core.result.Result.Ok 1#u64, st)
  | Expr.App f a =>
    let (r, st1) ← size fuel st f
    let cf ← core.result.Result.Insts.CoreOpsTry.branch r
    match cf with
    | core.ops.control_flow.ControlFlow.Continue val =>
      let (r1, st2) ← size fuel st1 a
      let cf1 ← core.result.Result.Insts.CoreOpsTry.branch r1
      match cf1 with
      | core.ops.control_flow.ControlFlow.Continue val1 =>
        let o ← lift (U64.checked_add val val1)
        match o with
        | none => ok (core.result.Result.Err CheckError.Overflow, st2)
        | some s =>
          let o1 ← lift (U64.checked_add s 1#u64)
          match o1 with
          | none => ok (core.result.Result.Err CheckError.Overflow, st2)
          | some t => ok (core.result.Result.Ok t, st2)
      | core.ops.control_flow.ControlFlow.Break residual =>
        let r2 ←
          core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
            Std.U64 (core.convert.FromSame CheckError) residual
        ok (r2, st2)
    | core.ops.control_flow.ControlFlow.Break residual =>
      let r1 ←
        core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
          Std.U64 (core.convert.FromSame CheckError) residual
      ok (r1, st1)
  | Expr.Lam b =>
    let (r, st1) ← size fuel st b
    let cf ← core.result.Result.Insts.CoreOpsTry.branch r
    match cf with
    | core.ops.control_flow.ControlFlow.Continue val =>
      let o ← lift (U64.checked_add val 1#u64)
      match o with
      | none => ok (core.result.Result.Err CheckError.Overflow, st1)
      | some t => ok (core.result.Result.Ok t, st1)
    | core.ops.control_flow.ControlFlow.Break residual =>
      let r1 ←
        core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
          Std.U64 (core.convert.FromSame CheckError) residual
      ok (r1, st1)
partial_fixpoint

end

end rc_fuel
