-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [rc_fuel]: type definitions
import Aeneas
import RcFuel.TypesExternal
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace rc_fuel

/-- Trait declaration: [core::alloc::AllocatorClone]
    Source: '/rustc/library/core/src/alloc/mod.rs', lines 531:0-531:50
    Name pattern: [core::alloc::AllocatorClone]
    Visibility: public -/
@[rust_trait "core::alloc::AllocatorClone"
  (parentClauses := ["cloneCloneInst"])]
structure core.alloc.AllocatorClone (Self : Type) where
  cloneCloneInst : core.clone.Clone Self

mutual

/-- [rc_fuel::Expr]
    Source: 'src/lib.rs', lines 5:0-9:1
    Visibility: public -/
@[discriminant isize]
inductive Expr where
| BVar : Std.U64 → Expr
| App : alloc.rc.Rc Node → alloc.rc.Rc Node → Expr
| Lam : alloc.rc.Rc Node → Expr

/-- [rc_fuel::Node]
    Source: 'src/lib.rs', lines 13:0-16:1
    Visibility: public -/
inductive Node where
| mk : Std.U64 → Expr → Node

end

def Node.data (x : Node) := match x with | Node.mk x1 _ => x1

def Node.expr (x : Node) := match x with | Node.mk _ x1 => x1

@[simp]
theorem Node.data._simpLemma_ (data : Std.U64) (expr : Expr) :
  (Node.mk data expr).data = data := by rfl

@[simp]
theorem Node.expr._simpLemma_ (data : Std.U64) (expr : Expr) :
  (Node.mk data expr).expr = expr := by rfl

/-- [rc_fuel::Memo]
    Source: 'src/lib.rs', lines 55:0-58:1
    Visibility: public -/
structure Memo where
  entries : alloc.vec.Vec ((alloc.rc.Rc Node) × Std.U64)
  hits : Std.U64

/-- [rc_fuel::CheckError]
    Source: 'src/lib.rs', lines 72:0-75:1
    Visibility: public -/
@[discriminant isize]
inductive CheckError where
| FuelExhausted : CheckError
| Overflow : CheckError

end rc_fuel
