/-
# `ConRon.Arena.Frontend.Prelude` — the built-in prelude (task #97e)

con-leche's `ConLeche/Frontend/Prelude.lean`: the checker's own little prelude
— the six pinned basis blocks (`Eq`, `Nat`, `PUnit`, `Empty`, `False`, `Quot`
with its soundness axiom), the `Bool` block, and the `And` block pinned by
design — as a lean4export-format stream parsed by the ORDINARY parser
(`parseBytes`, which is what `parseExportD` is) into declaration records.  `preparePrelude` puts them at the
front of every stream it prepares, which is what "in the env initially and
unconditionally" means in practice.

**Where the text comes from.**  con-leche's `builtinPreludeText` is an
`include_str` of its own committed `pins/<toolchain>.prelude.ndjson`.  Task
#97e part 1 made this the same `include_str` of the same file, reached through
the con-leche lake package directory — which made this module's `.olean`
depend on a path outside the repository, the objection
`scripts/gen-prelude.sh` raised for the Rust port at task #84.  Part 2 gives
(B) the same answer the Rust port got: the bytes are a **committed constant**,
`Arena/Frontend/PreludeText.lean`'s `preludeText`, generated by
`scripts/gen-prelude-lean.sh` from con-leche's own file and gated by its
`--check` (a step of `scripts/gates.sh`).  That module's note says why it
mirrors the Rust twin's 67-chunk splitting and why the chunks are bytes.

**Why the parse is monadic where con-leche's is a 0-ary `def`.**  con-leche
parses the text once at module initialisation, because its parse is pure and
its result owns nothing but `Expr` trees.  The arena's parse INTERNS into the
`EStore` the `AM` state carries, so the prelude's nodes must land in the same
store the stream's do — that is the whole point of the persistent tier — and
the driver runs this once, first, before the stream's own chunks.  It is the
same deviation `crates/con-ron-core/src/frontend/prelude.rs` records for the
Rust port, for the same reason.

The prelude has no mutual or nested block, so the `Modeller` it is parsed with
cannot change the result; the driver passes the same one it parses the stream
with, as the Rust port does.
-/
import ConRon.Arena.Frontend.Prepare
import ConRon.Arena.Frontend.PreludeText

namespace ConRon.Arena.Frontend

/-- con-leche: ConLeche/Frontend/Prelude.lean:64-68 builtinPreludeE — the
parsed, indexed prelude: an error channel because a committed file can in
principle be corrupted, and a prelude that does not parse must be a loud error
rather than a silently empty prelude.

`parseBytes` of `PreludeText.preludeText` where con-leche is `parseExportD` of
a `String` — the same parse, since `parseExportD` is `parseBytes` of the
string's UTF-8 and the committed constant is those bytes.  It is the deviation
`crates/con-ron-core/src/frontend/prelude.rs` records for the Rust port, for
the same reason. -/
def builtinPreludeE (md : Modeller) : AM (Except (CheckError × Nat) PreludeIx) := do
  match ← parseBytes md preludeText with
  | .error e => pure (.error e)
  | .ok r => pure (.ok ⟨r.decls⟩)

end ConRon.Arena.Frontend
