#!/usr/bin/env bash
# Style gate for the Aeneas-facing Rust (DESIGN.md §3.4).
# Usage: scripts/lint-rust-style.sh [dir ...]   (default: crates/con-ron-core/src)
#
# `#[cfg(test)]` modules are exempt: Charon never sees them (they are not in
# the non-test build), so they may use closures, iterators and loops.
set -u
dirs=("$@"); [ ${#dirs[@]} -eq 0 ] && dirs=(crates/con-ron-core/src)
# Every source line before the first `#[cfg(test)]`, as `file:line:text`.
gather() {
  local f
  find "${dirs[@]}" -name '*.rs' -type f 2>/dev/null | sort | while read -r f; do
    awk -v F="$f" '/#\[cfg\(test\)\]/ { exit } { printf "%s:%d:%s\n", F, NR, $0 }' "$f"
  done
}
fail=0
check() { # check <label> <regex>
  local label=$1 re=$2 hits
  hits=$(gather | grep -E "$re" | grep -v '^\S*:\S*:\s*//' | grep -v 'lint: allow')
  if [ -n "$hits" ]; then echo "== $label"; echo "$hits"; fail=1; fi
}
check "derive(Debug) (mixed recursion groups in Charon)" 'derive\([^)]*Debug'
# A closure bar has at least one character between the bars, which is what
# keeps `a || b` and `x | y` out (`||` and `|_|`-less bars are not closures).
check "closures" '\|\s*(_|mut |&|[a-z])[a-z_0-9,&: ]*\|\s*(\{|[a-z])'
check "? operator" '\)\?[;.) ]|\)\?$'
# Loops.  The rule is recursion (DESIGN.md §3.4); the ONE exemption is
# `crates/con-ron-core/src/frontend/`, the ported parser (task #84): the Lean
# it cites is a per-byte tail recursion that *Lean* compiles to a loop, and a
# per-byte recursion in Rust overflows the stack on a long export line.
# `-loops-to-rec` gives each loop a `foo_loop` function that mirrors the Lean
# recursion one for one.  (The `:[0-9]+:` is the `file:line:` prefix `gather`
# adds: a `^\s*` anchor here matched nothing at all until task #84 noticed.)
check_loops() {
  local hits
  hits=$(gather | grep -E ':[0-9]+:[[:space:]]*(while|for|loop)\b' \
    | grep -v '^\S*:\S*:\s*//' | grep -v 'lint: allow' \
    | grep -v 'con-ron-core/src/frontend/')   # unanchored: gates.sh passes an absolute dir
  if [ -n "$hits" ]; then
    echo "== loops (use recursion; only crates/con-ron-core/src/frontend/ may loop, DESIGN.md §3.4)"
    echo "$hits"; fail=1
  fi
}
check_loops
# `&str` CONSTANTS (task #86).  Aeneas emits one as `toStr "..."`, whose size
# bound it discharges with `by decide +native` in the constant's own
# definition, so the constant seals an axiom into every theorem whose closure
# reaches it (AENEAS_FINDINGS.md §3.8) -- and it prints an inner `"` unescaped
# (F17).  Spell a literal `const S: [u8; N] = *b"...";` and compare bytes.  A
# `&str` PARAMETER is fine; only a constant carries the axiom.  The ONE
# exception is `kernel/pins_text.rs`'s `PINS_TEXT`: 532 KB is past what an
# `Array.make` literal can hold, and the file is generated by
# `scripts/gen-pins.py`, so the exemption is by path rather than by an
# in-line `lint: allow` a regeneration would drop.
check_str_consts() {
  local hits
  hits=$(gather | grep -E 'const [A-Za-z_][A-Za-z0-9_]*[[:space:]]*:[[:space:]]*&([a-z'"'"']+ )?str\b' \
    | grep -v '^\S*:\S*:\s*//' | grep -v 'lint: allow' \
    | grep -v 'con-ron-core/src/kernel/pins_text.rs:')   # unanchored: gates.sh passes an absolute dir
  if [ -n "$hits" ]; then
    echo "== &str constants (toStr spends a decide+native axiom; use [u8; N], DESIGN.md §3.4)"
    echo "$hits"; fail=1
  fi
}
check_str_consts
# `unsafe`.  The rule is none at all (the 2026-09-12 ruling: `std` does it if
# it can).  The ONE exemption is `crates/con-ron-core/src/ron/node.rs`, the
# tagged `Expr` handle and its ten per-kind nodes (task #94): the kind lives in
# the handle's low four bits, so the pointee type is chosen at run time and no
# `std` smart pointer can express it.  Its surface is the module's own note,
# and `cargo test`'s `node.rs` round-trip plus `scripts/diff-e2e.sh` are what
# stand behind it.
check_unsafe() {
  local hits
  hits=$(gather | grep -E '\bunsafe\b' \
    | grep -v '^\S*:\S*:\s*//' | grep -v 'lint: allow' \
    | grep -v 'con-ron-core/src/ron/node.rs')   # unanchored: gates.sh passes an absolute dir
  if [ -n "$hits" ]; then
    echo "== unsafe (only crates/con-ron-core/src/ron/node.rs may, task #94)"
    echo "$hits"; fail=1
  fi
}
check_unsafe
check "std::collections" 'std::collections'
check "P/Rc/Arc API beyond new/clone/deref/ptr_eq" '\b(P|Rc|Arc)::(get_mut|make_mut|downgrade|try_unwrap|into_raw|from_raw|as_ptr|strong_count|weak_count|increment_strong_count|decrement_strong_count)|RefCell|Cell<'
check "panics as control flow" '\b(panic!|unwrap\(\)|expect\(|unreachable!|todo!|unimplemented!)'
exit $fail
