#!/usr/bin/env bash
# Style gate for the Aeneas-facing Rust (DESIGN.md §3.4).
# Usage: scripts/lint-rust-style.sh [dir ...]   (default: crates/con-ron-core/src)
#
# `#[cfg(test)]` modules are exempt: Charon never sees them (they are not in
# the non-test build), so they may use closures, iterators and loops.
set -u
dirs=("$@"); [ ${#dirs[@]} -eq 0 ] && dirs=(crates/con-ron-core/src)
# Every source line before the first `#[cfg(test)]`, as `file:line:text`.
gather() {
  local f
  find "${dirs[@]}" -name '*.rs' -type f 2>/dev/null | sort | while read -r f; do
    awk -v F="$f" '/#\[cfg\(test\)\]/ { exit } { printf "%s:%d:%s\n", F, NR, $0 }' "$f"
  done
}
fail=0
check() { # check <label> <regex>
  local label=$1 re=$2 hits
  hits=$(gather | grep -E "$re" | grep -v '^\S*:\S*:\s*//' | grep -v 'lint: allow')
  if [ -n "$hits" ]; then echo "== $label"; echo "$hits"; fail=1; fi
}
check "derive(Debug) (mixed recursion groups in Charon)" 'derive\([^)]*Debug'
# A closure bar has at least one character between the bars, which is what
# keeps `a || b` and `x | y` out (`||` and `|_|`-less bars are not closures).
check "closures" '\|\s*(_|mut |&|[a-z])[a-z_0-9,&: ]*\|\s*(\{|[a-z])'
check "? operator" '\)\?[;.) ]|\)\?$'
# Loops.  The rule is recursion (DESIGN.md §3.4); the exemption is the two
# ported PARSER directories -- `crates/con-ron-core/src/frontend/` (task #84)
# and `crates/arena-core/src/frontend/` (task #97 P4e, the same parser over
# store handles): the Lean they cite is a per-byte tail recursion that *Lean*
# compiles to a loop, and a per-byte recursion in Rust overflows the stack on
# a long export line.  `-loops-to-rec` gives each loop a `foo_loop` function
# that mirrors the Lean recursion one for one.  (The `:[0-9]+:` is the
# `file:line:` prefix `gather` adds: a `^\s*` anchor here matched nothing at
# all until task #84 noticed.)
check_loops() {
  local hits
  hits=$(gather | grep -E ':[0-9]+:[[:space:]]*(while|for|loop)\b' \
    | grep -v '^\S*:\S*:\s*//' | grep -v 'lint: allow' \
    | grep -vE '(con-ron-core|arena-core)/src/frontend/')   # unanchored: gates.sh passes an absolute dir
  if [ -n "$hits" ]; then
    echo "== loops (use recursion; only the two frontend/ directories may loop, DESIGN.md §3.4)"
    echo "$hits"; fail=1
  fi
}
check_loops
# `&str` CONSTANTS (task #86).  Aeneas emits one as `toStr "..."`, whose size
# bound it discharges with `by decide +native` in the constant's own
# definition, so the constant seals an axiom into every theorem whose closure
# reaches it (AENEAS_FINDINGS.md §3.8) -- and it prints an inner `"` unescaped
# (F17).  Spell a literal `const S: [u8; N] = *b"...";` and compare bytes.  A
# `&str` PARAMETER is fine; only a constant carries the axiom.  The ONE
# exception is `kernel/pins_text.rs`'s `PINS_TEXT`: 532 KB is past what an
# `Array.make` literal can hold, and the file is generated by
# `scripts/gen-pins.py`, so the exemption is by path rather than by an
# in-line `lint: allow` a regeneration would drop.
check_str_consts() {
  local hits
  hits=$(gather | grep -E 'const [A-Za-z_][A-Za-z0-9_]*[[:space:]]*:[[:space:]]*&([a-z'"'"']+ )?str\b' \
    | grep -v '^\S*:\S*:\s*//' | grep -v 'lint: allow' \
    | grep -v 'con-ron-core/src/kernel/pins_text.rs:')   # unanchored: gates.sh passes an absolute dir
  if [ -n "$hits" ]; then
    echo "== &str constants (toStr spends a decide+native axiom; use [u8; N], DESIGN.md §3.4)"
    echo "$hits"; fail=1
  fi
}
check_str_consts
# `unsafe`.  The rule is none at all (the 2026-09-12 ruling: `std` does it if
# it can).  The ONE exemption is `crates/con-ron-core/src/ron/tagged.rs`, the
# generic tagged counted handle (task #94): the kind lives in the handle's low
# four bits, so the pointee type is chosen at run time and no `std` smart
# pointer can express it.  That file names no term type; its instantiation for
# `Expr` (`ron/node.rs`) is a ten-line table and passes this lint like every
# other file.  The surface is `tagged.rs`'s own module note -- four expressions,
# two impls and one macro -- and `scripts/diff-e2e.sh` is what stands behind it.
check_unsafe() {
  local hits
  hits=$(gather | grep -E '\bunsafe\b' \
    | grep -v '^\S*:\S*:\s*//' | grep -v 'lint: allow' \
    | grep -v 'con-ron-core/src/ron/tagged.rs')   # unanchored: gates.sh passes an absolute dir
  if [ -n "$hits" ]; then
    echo "== unsafe (only crates/con-ron-core/src/ron/tagged.rs may, task #94)"
    echo "$hits"; fail=1
  fi
}
check_unsafe
check "std::collections" 'std::collections'
# The counted-pointer API, and what the rule is actually about.  The banned
# names all let the count or the pointee ESCAPE into a value the model cannot
# see: `get_mut`/`make_mut` mutate THROUGH a share, which is exactly what "an
# `Arc` is its contents" cannot express; `strong_count` puts the count itself
# into a number a program can compute with; the raw-pointer and `Weak` names
# hand out identities.  A *read of the count that only selects an equivalent
# path* is a different thing and is allowed — `ron::tagged::Raw::is_exclusive`,
# the port of con-leche's `withExclusive` (task #98), whose answer never
# reaches a value and whose model is `false`, the branch that always memoises
# (OVERVIEW.md §8.1's row argues it).  It is deliberately NOT spelled
# `Arc::strong_count`: it is one method on the crate's own handle, `pub(crate)`
# like the rest of `tagged.rs`, reachable from the core through the single
# `ron::node::is_exclusive`, and the names below stay banned so that nothing
# reads an `Arc`'s count -- `Name`, `Level`, `PropWhen` and `ConstantInfo`
# are still `Arc` and nothing needs their counts.
check "P/Rc/Arc API beyond new/clone/deref/ptr_eq" '\b(P|Rc|Arc)::(get_mut|make_mut|downgrade|try_unwrap|into_raw|from_raw|as_ptr|strong_count|weak_count|increment_strong_count|decrement_strong_count)|RefCell|Cell<'
check "panics as control flow" '\b(panic!|unwrap\(\)|expect\(|unreachable!|todo!|unimplemented!)'
exit $fail
